import { chromium } from '/home/daniel/citybox/node_modules/.pnpm/@playwright+test@1.60.0/node_modules/@playwright/test/index.mjs';
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true });
const page = await browser.newPage();
await page.goto('http://localhost:3111/login', { waitUntil: 'networkidle', timeout: 30000 });
await page.getByRole('button', { name: /Entrar/i }).first().click();
await page.waitForTimeout(3000);
await page.fill('#username', 'lojista@citybox.com');
await page.fill('#password', 'citybox');
await page.click('#kc-login');
await page.waitForTimeout(5000);
console.log('url:', page.url().slice(0, 140));
const inputs = await page.$$eval('input', (els) => els.map((e) => ({ id: e.id, name: e.name, type: e.type })));
console.log('inputs:', JSON.stringify(inputs, null, 1));
const text = await page.evaluate(() => document.body ? document.body.innerText.slice(0, 800) : '');
console.log('texto da pagina:\n---\n' + text + '\n---');
await page.screenshot({ path: '/tmp/opencode/kc-step.png' });
await browser.close();
