/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.AddressEnvelopeData
import com.citybox.api.models.Address

class AddressEnvelopeDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddressEnvelopeData
        //val modelInstance = AddressEnvelopeData()

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

    }
}
