/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.AddReviewPhoto201ResponseData
import com.citybox.api.models.Review

class AddReviewPhoto201ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddReviewPhoto201ResponseData
        //val modelInstance = AddReviewPhoto201ResponseData()

        // to test the property `photoUrl`
        should("test photoUrl") {
            // uncomment below to test the property
            //modelInstance.photoUrl shouldBe ("TODO")
        }

        // to test the property `review`
        should("test review") {
            // uncomment below to test the property
            //modelInstance.review shouldBe ("TODO")
        }

    }
}
