/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.AddressInput

class AddressInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddressInput
        //val modelInstance = AddressInput()

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `zipCode`
        should("test zipCode") {
            // uncomment below to test the property
            //modelInstance.zipCode shouldBe ("TODO")
        }

        // to test the property `street`
        should("test street") {
            // uncomment below to test the property
            //modelInstance.street shouldBe ("TODO")
        }

        // to test the property `number`
        should("test number") {
            // uncomment below to test the property
            //modelInstance.number shouldBe ("TODO")
        }

        // to test the property `neighborhood`
        should("test neighborhood") {
            // uncomment below to test the property
            //modelInstance.neighborhood shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `complement`
        should("test complement") {
            // uncomment below to test the property
            //modelInstance.complement shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

    }
}
