/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CancelSubscriptionRequest

class CancelSubscriptionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CancelSubscriptionRequest
        //val modelInstance = CancelSubscriptionRequest()

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `feedback`
        should("test feedback") {
            // uncomment below to test the property
            //modelInstance.feedback shouldBe ("TODO")
        }

    }
}
