/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Cart
import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.CartItem
import com.citybox.api.models.CartShippingPreview

class CartTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Cart
        //val modelInstance = Cart()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `itemCount`
        should("test itemCount") {
            // uncomment below to test the property
            //modelInstance.itemCount shouldBe ("TODO")
        }

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `appliedCoupon`
        should("test appliedCoupon") {
            // uncomment below to test the property
            //modelInstance.appliedCoupon shouldBe ("TODO")
        }

        // to test the property `couponDiscount`
        should("test couponDiscount") {
            // uncomment below to test the property
            //modelInstance.couponDiscount shouldBe ("TODO")
        }

        // to test the property `shippingPreview`
        should("test shippingPreview") {
            // uncomment below to test the property
            //modelInstance.shippingPreview shouldBe ("TODO")
        }

    }
}
