/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CartShippingPreview

class CartShippingPreviewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartShippingPreview
        //val modelInstance = CartShippingPreview()

        // to test the property `selectedOptionId`
        should("test selectedOptionId") {
            // uncomment below to test the property
            //modelInstance.selectedOptionId shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `freeShippingMessage`
        should("test freeShippingMessage") {
            // uncomment below to test the property
            //modelInstance.freeShippingMessage shouldBe ("TODO")
        }

    }
}
