/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CheckoutSession
import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.PaymentType

class CheckoutSessionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutSession
        //val modelInstance = CheckoutSession()

        // to test the property `selectedAddressId`
        should("test selectedAddressId") {
            // uncomment below to test the property
            //modelInstance.selectedAddressId shouldBe ("TODO")
        }

        // to test the property `shippingOptionId`
        should("test shippingOptionId") {
            // uncomment below to test the property
            //modelInstance.shippingOptionId shouldBe ("TODO")
        }

        // to test the property `appliedCoupon`
        should("test appliedCoupon") {
            // uncomment below to test the property
            //modelInstance.appliedCoupon shouldBe ("TODO")
        }

        // to test the property `paymentType`
        should("test paymentType") {
            // uncomment below to test the property
            //modelInstance.paymentType shouldBe ("TODO")
        }

        // to test the property `paymentMethodId`
        should("test paymentMethodId") {
            // uncomment below to test the property
            //modelInstance.paymentMethodId shouldBe ("TODO")
        }

        // to test the property `boletoCpf`
        should("test boletoCpf") {
            // uncomment below to test the property
            //modelInstance.boletoCpf shouldBe ("TODO")
        }

        // to test the property `canConfirm`
        should("test canConfirm") {
            // uncomment below to test the property
            //modelInstance.canConfirm shouldBe ("TODO")
        }

    }
}
