/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CheckoutSessionEnvelopeData
import com.citybox.api.models.Cart
import com.citybox.api.models.CheckoutPreview
import com.citybox.api.models.CheckoutSession

class CheckoutSessionEnvelopeDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutSessionEnvelopeData
        //val modelInstance = CheckoutSessionEnvelopeData()

        // to test the property `cart`
        should("test cart") {
            // uncomment below to test the property
            //modelInstance.cart shouldBe ("TODO")
        }

        // to test the property `session`
        should("test session") {
            // uncomment below to test the property
            //modelInstance.session shouldBe ("TODO")
        }

        // to test the property `preview`
        should("test preview") {
            // uncomment below to test the property
            //modelInstance.preview shouldBe ("TODO")
        }

    }
}
