/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CheckoutPreviewRequest
import com.citybox.api.models.CartItemInput
import com.citybox.api.models.PaymentType

class CheckoutPreviewRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutPreviewRequest
        //val modelInstance = CheckoutPreviewRequest()

        // to test the property `addressId`
        should("test addressId") {
            // uncomment below to test the property
            //modelInstance.addressId shouldBe ("TODO")
        }

        // to test the property `shippingOptionId`
        should("test shippingOptionId") {
            // uncomment below to test the property
            //modelInstance.shippingOptionId shouldBe ("TODO")
        }

        // to test the property `couponCode`
        should("test couponCode") {
            // uncomment below to test the property
            //modelInstance.couponCode shouldBe ("TODO")
        }

        // to test the property `paymentType`
        should("test paymentType") {
            // uncomment below to test the property
            //modelInstance.paymentType shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
