/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CheckoutPreview200ResponseData
import com.citybox.api.models.CheckoutPreview200ResponseDataAllOfInstallmentOptionsInner

class CheckoutPreview200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutPreview200ResponseData
        //val modelInstance = CheckoutPreview200ResponseData()

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `shipping`
        should("test shipping") {
            // uncomment below to test the property
            //modelInstance.shipping shouldBe ("TODO")
        }

        // to test the property `couponDiscount`
        should("test couponDiscount") {
            // uncomment below to test the property
            //modelInstance.couponDiscount shouldBe ("TODO")
        }

        // to test the property `pixDiscount`
        should("test pixDiscount") {
            // uncomment below to test the property
            //modelInstance.pixDiscount shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `pixDiscountPercent`
        should("test pixDiscountPercent") {
            // uncomment below to test the property
            //modelInstance.pixDiscountPercent shouldBe ("TODO")
        }

        // to test the property `installmentOptions`
        should("test installmentOptions") {
            // uncomment below to test the property
            //modelInstance.installmentOptions shouldBe ("TODO")
        }

        // to test the property `canConfirm`
        should("test canConfirm") {
            // uncomment below to test the property
            //modelInstance.canConfirm shouldBe ("TODO")
        }

        // to test the property `validationErrors`
        should("test validationErrors") {
            // uncomment below to test the property
            //modelInstance.validationErrors shouldBe ("TODO")
        }

    }
}
