/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CreatePaymentMethod201ResponseData
import com.citybox.api.models.PaymentMethod

class CreatePaymentMethod201ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePaymentMethod201ResponseData
        //val modelInstance = CreatePaymentMethod201ResponseData()

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

    }
}
