/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CreatePaymentMethodRequest

class CreatePaymentMethodRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePaymentMethodRequest
        //val modelInstance = CreatePaymentMethodRequest()

        // to test the property `number`
        should("test number") {
            // uncomment below to test the property
            //modelInstance.number shouldBe ("TODO")
        }

        // to test the property `holderName`
        should("test holderName") {
            // uncomment below to test the property
            //modelInstance.holderName shouldBe ("TODO")
        }

        // to test the property `expiry`
        should("test expiry") {
            // uncomment below to test the property
            //modelInstance.expiry shouldBe ("TODO")
        }

        // to test the property `cvv`
        should("test cvv") {
            // uncomment below to test the property
            //modelInstance.cvv shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

    }
}
