/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CreateReviewRequest

class CreateReviewRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateReviewRequest
        //val modelInstance = CreateReviewRequest()

        // to test the property `rating`
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `photoUrls`
        should("test photoUrls") {
            // uncomment below to test the property
            //modelInstance.photoUrls shouldBe ("TODO")
        }

    }
}
