/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.CreateOrderRequest
import com.citybox.api.models.CartItemInput
import com.citybox.api.models.PaymentInput

class CreateOrderRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateOrderRequest
        //val modelInstance = CreateOrderRequest()

        // to test the property `payment`
        should("test payment") {
            // uncomment below to test the property
            //modelInstance.payment shouldBe ("TODO")
        }

        // to test the property `addressId`
        should("test addressId") {
            // uncomment below to test the property
            //modelInstance.addressId shouldBe ("TODO")
        }

        // to test the property `shippingOptionId`
        should("test shippingOptionId") {
            // uncomment below to test the property
            //modelInstance.shippingOptionId shouldBe ("TODO")
        }

        // to test the property `couponCode`
        should("test couponCode") {
            // uncomment below to test the property
            //modelInstance.couponCode shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `buyNow`
        should("test buyNow") {
            // uncomment below to test the property
            //modelInstance.buyNow shouldBe ("TODO")
        }

    }
}
