/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.FaqItem

class FaqItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FaqItem
        //val modelInstance = FaqItem()

        // to test the property `question`
        should("test question") {
            // uncomment below to test the property
            //modelInstance.question shouldBe ("TODO")
        }

        // to test the property `answer`
        should("test answer") {
            // uncomment below to test the property
            //modelInstance.answer shouldBe ("TODO")
        }

    }
}
