/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.GetFiltersMetadata200ResponseData
import com.citybox.api.models.GetFiltersMetadata200ResponseDataFlagsInner
import com.citybox.api.models.GetFiltersMetadata200ResponseDataPriceRange
import com.citybox.api.models.GetFiltersMetadata200ResponseDataSortOptionsInner

class GetFiltersMetadata200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFiltersMetadata200ResponseData
        //val modelInstance = GetFiltersMetadata200ResponseData()

        // to test the property `brands`
        should("test brands") {
            // uncomment below to test the property
            //modelInstance.brands shouldBe ("TODO")
        }

        // to test the property `priceRange`
        should("test priceRange") {
            // uncomment below to test the property
            //modelInstance.priceRange shouldBe ("TODO")
        }

        // to test the property `sortOptions`
        should("test sortOptions") {
            // uncomment below to test the property
            //modelInstance.sortOptions shouldBe ("TODO")
        }

        // to test the property `ratingOptions`
        should("test ratingOptions") {
            // uncomment below to test the property
            //modelInstance.ratingOptions shouldBe ("TODO")
        }

        // to test the property `flags`
        should("test flags") {
            // uncomment below to test the property
            //modelInstance.flags shouldBe ("TODO")
        }

    }
}
