/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.GetFiltersMetadata200ResponseDataPriceRange

class GetFiltersMetadata200ResponseDataPriceRangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFiltersMetadata200ResponseDataPriceRange
        //val modelInstance = GetFiltersMetadata200ResponseDataPriceRange()

        // to test the property `min`
        should("test min") {
            // uncomment below to test the property
            //modelInstance.min shouldBe ("TODO")
        }

        // to test the property `max`
        should("test max") {
            // uncomment below to test the property
            //modelInstance.max shouldBe ("TODO")
        }

    }
}
