/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.GetInvoice200ResponseData

class GetInvoice200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetInvoice200ResponseData
        //val modelInstance = GetInvoice200ResponseData()

        // to test the property `invoiceUrl`
        should("test invoiceUrl") {
            // uncomment below to test the property
            //modelInstance.invoiceUrl shouldBe ("TODO")
        }

        // to test the property `nfKey`
        should("test nfKey") {
            // uncomment below to test the property
            //modelInstance.nfKey shouldBe ("TODO")
        }

        // to test the property `issuedAt`
        should("test issuedAt") {
            // uncomment below to test the property
            //modelInstance.issuedAt shouldBe ("TODO")
        }

    }
}
