/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.GetProduct200ResponseData
import com.citybox.api.models.Product

class GetProduct200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProduct200ResponseData
        //val modelInstance = GetProduct200ResponseData()

        // to test the property `product`
        should("test product") {
            // uncomment below to test the property
            //modelInstance.product shouldBe ("TODO")
        }

        // to test the property `installmentCount`
        should("test installmentCount") {
            // uncomment below to test the property
            //modelInstance.installmentCount shouldBe ("TODO")
        }

        // to test the property `installmentValue`
        should("test installmentValue") {
            // uncomment below to test the property
            //modelInstance.installmentValue shouldBe ("TODO")
        }

    }
}
