/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.GetShippingOptions200ResponseData
import com.citybox.api.models.ShippingOption

class GetShippingOptions200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetShippingOptions200ResponseData
        //val modelInstance = GetShippingOptions200ResponseData()

        // to test the property `options`
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

        // to test the property `freeShippingMessage`
        should("test freeShippingMessage") {
            // uncomment below to test the property
            //modelInstance.freeShippingMessage shouldBe ("TODO")
        }

    }
}
