/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.ListPaymentMethods200ResponseData
import com.citybox.api.models.PaymentMethod

class ListPaymentMethods200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListPaymentMethods200ResponseData
        //val modelInstance = ListPaymentMethods200ResponseData()

        // to test the property `paymentMethods`
        should("test paymentMethods") {
            // uncomment below to test the property
            //modelInstance.paymentMethods shouldBe ("TODO")
        }

    }
}
