/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.ListFavorites200ResponseData
import com.citybox.api.models.Product

class ListFavorites200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListFavorites200ResponseData
        //val modelInstance = ListFavorites200ResponseData()

        // to test the property `productIds`
        should("test productIds") {
            // uncomment below to test the property
            //modelInstance.productIds shouldBe ("TODO")
        }

        // to test the property `products`
        should("test products") {
            // uncomment below to test the property
            //modelInstance.products shouldBe ("TODO")
        }

    }
}
