/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.LoginGoogleRequest

class LoginGoogleRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoginGoogleRequest
        //val modelInstance = LoginGoogleRequest()

        // to test the property `idToken`
        should("test idToken") {
            // uncomment below to test the property
            //modelInstance.idToken shouldBe ("TODO")
        }

        // to test the property `hasSeenOnboarding`
        should("test hasSeenOnboarding") {
            // uncomment below to test the property
            //modelInstance.hasSeenOnboarding shouldBe ("TODO")
        }

    }
}
