/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.MarkNotificationRead200ResponseData
import com.citybox.api.models.Notification

class MarkNotificationRead200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarkNotificationRead200ResponseData
        //val modelInstance = MarkNotificationRead200ResponseData()

        // to test the property `notification`
        should("test notification") {
            // uncomment below to test the property
            //modelInstance.notification shouldBe ("TODO")
        }

        // to test the property `unreadCount`
        should("test unreadCount") {
            // uncomment below to test the property
            //modelInstance.unreadCount shouldBe ("TODO")
        }

    }
}
