/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Order
import com.citybox.api.models.Address
import com.citybox.api.models.OrderItem
import com.citybox.api.models.OrderPaymentMethod
import com.citybox.api.models.OrderStatus
import com.citybox.api.models.OrderStatusEntry

class OrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Order
        //val modelInstance = Order()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `deliveryDate`
        should("test deliveryDate") {
            // uncomment below to test the property
            //modelInstance.deliveryDate shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `shipping`
        should("test shipping") {
            // uncomment below to test the property
            //modelInstance.shipping shouldBe ("TODO")
        }

        // to test the property `discount`
        should("test discount") {
            // uncomment below to test the property
            //modelInstance.discount shouldBe ("TODO")
        }

        // to test the property `pixDiscount`
        should("test pixDiscount") {
            // uncomment below to test the property
            //modelInstance.pixDiscount shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `trackingCode`
        should("test trackingCode") {
            // uncomment below to test the property
            //modelInstance.trackingCode shouldBe ("TODO")
        }

        // to test the property `carrier`
        should("test carrier") {
            // uncomment below to test the property
            //modelInstance.carrier shouldBe ("TODO")
        }

        // to test the property `statusHistory`
        should("test statusHistory") {
            // uncomment below to test the property
            //modelInstance.statusHistory shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
