/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.PaymentResult
import com.citybox.api.models.PaymentType

class PaymentResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentResult
        //val modelInstance = PaymentResult()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `paymentMethodId`
        should("test paymentMethodId") {
            // uncomment below to test the property
            //modelInstance.paymentMethodId shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `authorizationCode`
        should("test authorizationCode") {
            // uncomment below to test the property
            //modelInstance.authorizationCode shouldBe ("TODO")
        }

        // to test the property `pixQrCodeBase64`
        should("test pixQrCodeBase64") {
            // uncomment below to test the property
            //modelInstance.pixQrCodeBase64 shouldBe ("TODO")
        }

        // to test the property `pixCopyPaste`
        should("test pixCopyPaste") {
            // uncomment below to test the property
            //modelInstance.pixCopyPaste shouldBe ("TODO")
        }

        // to test the property `barcode`
        should("test barcode") {
            // uncomment below to test the property
            //modelInstance.barcode shouldBe ("TODO")
        }

        // to test the property `digitableLine`
        should("test digitableLine") {
            // uncomment below to test the property
            //modelInstance.digitableLine shouldBe ("TODO")
        }

        // to test the property `dueDate`
        should("test dueDate") {
            // uncomment below to test the property
            //modelInstance.dueDate shouldBe ("TODO")
        }

        // to test the property `pdfUrl`
        should("test pdfUrl") {
            // uncomment below to test the property
            //modelInstance.pdfUrl shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
