/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.PaymentMethod
import com.citybox.api.models.CardBrand

class PaymentMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethod
        //val modelInstance = PaymentMethod()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `brand`
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `lastFour`
        should("test lastFour") {
            // uncomment below to test the property
            //modelInstance.lastFour shouldBe ("TODO")
        }

        // to test the property `expiry`
        should("test expiry") {
            // uncomment below to test the property
            //modelInstance.expiry shouldBe ("TODO")
        }

        // to test the property `holderName`
        should("test holderName") {
            // uncomment below to test the property
            //modelInstance.holderName shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

    }
}
