/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.PaymentInput
import com.citybox.api.models.PaymentType

class PaymentInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentInput
        //val modelInstance = PaymentInput()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `paymentMethodId` - Obrigatório quando type=CARD
        should("test paymentMethodId") {
            // uncomment below to test the property
            //modelInstance.paymentMethodId shouldBe ("TODO")
        }

        // to test the property `cpf` - Obrigatório quando type=BOLETO
        should("test cpf") {
            // uncomment below to test the property
            //modelInstance.cpf shouldBe ("TODO")
        }

    }
}
