/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Product

class ProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Product
        //val modelInstance = Product()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `originalPrice`
        should("test originalPrice") {
            // uncomment below to test the property
            //modelInstance.originalPrice shouldBe ("TODO")
        }

        // to test the property `discountPercent`
        should("test discountPercent") {
            // uncomment below to test the property
            //modelInstance.discountPercent shouldBe ("TODO")
        }

        // to test the property `rating`
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `reviewCount`
        should("test reviewCount") {
            // uncomment below to test the property
            //modelInstance.reviewCount shouldBe ("TODO")
        }

        // to test the property `isFreeShipping`
        should("test isFreeShipping") {
            // uncomment below to test the property
            //modelInstance.isFreeShipping shouldBe ("TODO")
        }

        // to test the property `isExpress`
        should("test isExpress") {
            // uncomment below to test the property
            //modelInstance.isExpress shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `categoryId`
        should("test categoryId") {
            // uncomment below to test the property
            //modelInstance.categoryId shouldBe ("TODO")
        }

        // to test the property `brand`
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `specs`
        should("test specs") {
            // uncomment below to test the property
            //modelInstance.specs shouldBe ("TODO")
        }

    }
}
