/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.RegisterRequest

class RegisterRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegisterRequest
        //val modelInstance = RegisterRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `confirmPassword`
        should("test confirmPassword") {
            // uncomment below to test the property
            //modelInstance.confirmPassword shouldBe ("TODO")
        }

        // to test the property `acceptedTerms`
        should("test acceptedTerms") {
            // uncomment below to test the property
            //modelInstance.acceptedTerms shouldBe ("TODO")
        }

        // to test the property `hasSeenOnboarding`
        should("test hasSeenOnboarding") {
            // uncomment below to test the property
            //modelInstance.hasSeenOnboarding shouldBe ("TODO")
        }

    }
}
