/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.RemoveCoupon200ResponseData
import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.CheckoutPreview

class RemoveCoupon200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RemoveCoupon200ResponseData
        //val modelInstance = RemoveCoupon200ResponseData()

        // to test the property `appliedCoupon`
        should("test appliedCoupon") {
            // uncomment below to test the property
            //modelInstance.appliedCoupon shouldBe ("TODO")
        }

        // to test the property `preview`
        should("test preview") {
            // uncomment below to test the property
            //modelInstance.preview shouldBe ("TODO")
        }

    }
}
