/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.SendChatMessage201ResponseData
import com.citybox.api.models.ChatMessage

class SendChatMessage201ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendChatMessage201ResponseData
        //val modelInstance = SendChatMessage201ResponseData()

        // to test the property `userMessage`
        should("test userMessage") {
            // uncomment below to test the property
            //modelInstance.userMessage shouldBe ("TODO")
        }

        // to test the property `agentMessage`
        should("test agentMessage") {
            // uncomment below to test the property
            //modelInstance.agentMessage shouldBe ("TODO")
        }

    }
}
