/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Settings

class SettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Settings
        //val modelInstance = Settings()

        // to test the property `pushOrdersEnabled`
        should("test pushOrdersEnabled") {
            // uncomment below to test the property
            //modelInstance.pushOrdersEnabled shouldBe ("TODO")
        }

        // to test the property `pushPromoEnabled`
        should("test pushPromoEnabled") {
            // uncomment below to test the property
            //modelInstance.pushPromoEnabled shouldBe ("TODO")
        }

        // to test the property `emailPromoEnabled`
        should("test emailPromoEnabled") {
            // uncomment below to test the property
            //modelInstance.emailPromoEnabled shouldBe ("TODO")
        }

        // to test the property `darkTheme`
        should("test darkTheme") {
            // uncomment below to test the property
            //modelInstance.darkTheme shouldBe ("TODO")
        }

        // to test the property `language`
        should("test language") {
            // uncomment below to test the property
            //modelInstance.language shouldBe ("TODO")
        }

    }
}
