/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.ShippingOption

class ShippingOptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShippingOption
        //val modelInstance = ShippingOption()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `deliveryEstimate`
        should("test deliveryEstimate") {
            // uncomment below to test the property
            //modelInstance.deliveryEstimate shouldBe ("TODO")
        }

        // to test the property `deliveryEstimateDays`
        should("test deliveryEstimateDays") {
            // uncomment below to test the property
            //modelInstance.deliveryEstimateDays shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `isExpress`
        should("test isExpress") {
            // uncomment below to test the property
            //modelInstance.isExpress shouldBe ("TODO")
        }

    }
}
