/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Subscription

class SubscriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Subscription
        //val modelInstance = Subscription()

        // to test the property `isActive`
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `planName`
        should("test planName") {
            // uncomment below to test the property
            //modelInstance.planName shouldBe ("TODO")
        }

        // to test the property `priceMonthly`
        should("test priceMonthly") {
            // uncomment below to test the property
            //modelInstance.priceMonthly shouldBe ("TODO")
        }

        // to test the property `renewalDate`
        should("test renewalDate") {
            // uncomment below to test the property
            //modelInstance.renewalDate shouldBe ("TODO")
        }

        // to test the property `benefits`
        should("test benefits") {
            // uncomment below to test the property
            //modelInstance.benefits shouldBe ("TODO")
        }

    }
}
