/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.ToggleFavoriteRequest

class ToggleFavoriteRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ToggleFavoriteRequest
        //val modelInstance = ToggleFavoriteRequest()

        // to test the property `isFavorite`
        should("test isFavorite") {
            // uncomment below to test the property
            //modelInstance.isFavorite shouldBe ("TODO")
        }

    }
}
