/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.Tracking
import com.citybox.api.models.OrderStatus
import com.citybox.api.models.TrackingTimelineInner

class TrackingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Tracking
        //val modelInstance = Tracking()

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `trackingCode`
        should("test trackingCode") {
            // uncomment below to test the property
            //modelInstance.trackingCode shouldBe ("TODO")
        }

        // to test the property `carrier`
        should("test carrier") {
            // uncomment below to test the property
            //modelInstance.carrier shouldBe ("TODO")
        }

        // to test the property `carrierUrl`
        should("test carrierUrl") {
            // uncomment below to test the property
            //modelInstance.carrierUrl shouldBe ("TODO")
        }

        // to test the property `currentStatus`
        should("test currentStatus") {
            // uncomment below to test the property
            //modelInstance.currentStatus shouldBe ("TODO")
        }

        // to test the property `estimatedDelivery`
        should("test estimatedDelivery") {
            // uncomment below to test the property
            //modelInstance.estimatedDelivery shouldBe ("TODO")
        }

        // to test the property `timeline`
        should("test timeline") {
            // uncomment below to test the property
            //modelInstance.timeline shouldBe ("TODO")
        }

        // to test the property `mapPlaceholderUrl`
        should("test mapPlaceholderUrl") {
            // uncomment below to test the property
            //modelInstance.mapPlaceholderUrl shouldBe ("TODO")
        }

    }
}
