/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `avatarUrl`
        should("test avatarUrl") {
            // uncomment below to test the property
            //modelInstance.avatarUrl shouldBe ("TODO")
        }

        // to test the property `avatarInitial`
        should("test avatarInitial") {
            // uncomment below to test the property
            //modelInstance.avatarInitial shouldBe ("TODO")
        }

        // to test the property `isPlus`
        should("test isPlus") {
            // uncomment below to test the property
            //modelInstance.isPlus shouldBe ("TODO")
        }

        // to test the property `hasSeenOnboarding`
        should("test hasSeenOnboarding") {
            // uncomment below to test the property
            //modelInstance.hasSeenOnboarding shouldBe ("TODO")
        }

    }
}
