/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.models.ValidateCoupon200ResponseData
import com.citybox.api.models.Coupon

class ValidateCoupon200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateCoupon200ResponseData
        //val modelInstance = ValidateCoupon200ResponseData()

        // to test the property `coupon`
        should("test coupon") {
            // uncomment below to test the property
            //modelInstance.coupon shouldBe ("TODO")
        }

        // to test the property `discountAmount`
        should("test discountAmount") {
            // uncomment below to test the property
            //modelInstance.discountAmount shouldBe ("TODO")
        }

        // to test the property `isValid`
        should("test isValid") {
            // uncomment below to test the property
            //modelInstance.isValid shouldBe ("TODO")
        }

    }
}
