"use client";
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, BookOpen, CheckCircle2, Circle, GitBranch, History, ListChecks, MessageSquareText, Save, Send, ShieldCheck, Sparkles, XCircle } from 'lucide-react';
import { BotaoPrimario } from '@/components/ui/BotaoPrimario';
import { EditorFluxo } from './EditorFluxo';
import { processoAtualizar, processoObter, processoTransicionar } from '@/services/api/processos';
import { corSituacao, rotuloProcesso } from './PainelProcessos';
import { normalizarEtapas } from '@/lib/processos-fluxo';

const perguntas = [
  ['inicio','Como o processo começa?'],['iniciador','Quem pode iniciá-lo?'],['dados','Quais dados são obrigatórios?'],['recebedor','Quem recebe a demanda?'],['etapasTexto','Quais são as etapas?'],['executores','Quem executa cada etapa?'],['aprovacao','Existe aprovação? Quem aprova?'],['prazo','Qual é o prazo?'],['retorno','O que faz o processo retornar?'],['excecoes','Quais são as exceções?'],['documentos','Quais documentos são usados?'],['sistemas','Qual sistema é utilizado atualmente?'],['gargalos','Quais gargalos existem?'],['termino','Como sabemos que terminou?'],['indicadores','Quais indicadores devem ser acompanhados?'],['automacao','O que pode ser automatizado?'],['ia','Onde a IA pode ajudar?'],
] as const;
type Aba = 'resumo'|'entrevista'|'fluxo'|'manual'|'validacao'|'historico';
const abas: Array<[Aba,string,typeof BookOpen]> = [['resumo','Visão geral',ListChecks],['entrevista','Entrevista',MessageSquareText],['fluxo','Fluxograma',GitBranch],['manual','Manual',BookOpen],['validacao','Validação',ShieldCheck],['historico','Histórico',History]];

export function WorkspaceProcesso({ id }: { id: string }) {
  const qc=useQueryClient(); const q=useQuery({queryKey:['processo',id],queryFn:()=>processoObter(id)}); const [aba,setAba]=useState<Aba>('resumo');
  const [entrevista,setEntrevista]=useState<Record<string,unknown>>({}); const [manual,setManual]=useState<Record<string,unknown>>({}); const [estadoSave,setEstadoSave]=useState<'salvo'|'alterado'|'salvando'>('salvo'); const [erro,setErro]=useState('');
  useEffect(()=>{if(q.data){setEntrevista(q.data.entrevista??{});setManual(q.data.manual??{});}},[q.data]);
  const salvar=useMutation({mutationFn:()=>processoAtualizar(id,{revisao:q.data!.revisao,entrevista,manual}),onMutate:()=>setEstadoSave('salvando'),onSuccess:(p)=>{qc.setQueryData(['processo',id],p);setEstadoSave('salvo');},onError:(e:Error)=>{setErro(e.message);setEstadoSave('alterado');}});
  const transicao=useMutation({mutationFn:({acao,motivo}:{acao:string;motivo?:string})=>processoTransicionar(id,acao,motivo),onSuccess:()=>qc.invalidateQueries({queryKey:['processo',id]})});
  useEffect(()=>{if(estadoSave!=='alterado'||!q.data)return;const t=setTimeout(()=>salvar.mutate(),1400);return()=>clearTimeout(t);},[entrevista,manual,estadoSave]); // eslint-disable-line react-hooks/exhaustive-deps
  const mudarEntrevista=(k:string,v:string)=>{setEntrevista(a=>({...a,[k]:v}));setEstadoSave('alterado');};
  const mudarManual=(k:string,v:string)=>{setManual(a=>({...a,[k]:v}));setEstadoSave('alterado');};
  const etapas=useMemo(()=>normalizarEtapas(entrevista.etapas,String(entrevista.etapasTexto??'')),[entrevista.etapas,entrevista.etapasTexto]);
  const mudarEtapas=(novas: ReturnType<typeof normalizarEtapas>)=>{setEntrevista(a=>({...a,etapas:novas}));setEstadoSave('alterado');};
  if(q.isLoading)return <div className="pc-loading"><Sparkles className="pc-pulse"/>Abrindo área de trabalho…</div>;
  if(!q.data)return <div className="pc-error-state">Processo não encontrado.</div>; const p=q.data; const travado=['aprovado','implantado','arquivado','substituido'].includes(p.situacao);
  return <main className="pc-workspace"><header className="pc-work-head"><div className="pc-work-title"><Link href="/processos" className="pc-back"><ArrowLeft size={18}/></Link><div><div className="pc-breadcrumb">Central de Processos <span>/</span> {p.codigo}</div><h1>{p.nome}</h1><div className="pc-work-meta"><span className="pc-status" style={{'--status':corSituacao[p.situacao]??'#3976a8'} as React.CSSProperties}>{rotuloProcesso(p.situacao)}</span><span>{rotuloProcesso(p.setorPrincipal)}</span><span>Versão {p.versaoAtual}</span></div></div></div><div className={`pc-save-state pc-save-${estadoSave}`}><Save size={15}/>{estadoSave==='salvando'?'Salvando…':estadoSave==='alterado'?'Alterações pendentes':'Salvo'}</div></header>
    <nav className="pc-tabs" aria-label="Modos do processo">{abas.map(([key,label,Icon])=><button key={key} onClick={()=>setAba(key)} className={aba===key?'ativo':''}><Icon size={16}/>{label}</button>)}</nav>
    {erro&&<div className="pc-inline-error">{erro}<button onClick={()=>setErro('')}>×</button></div>}
    <section className="pc-work-body">
      {aba==='resumo'&&<div className="pc-summary-grid"><article className="pc-panel pc-summary-main"><span className="pc-kicker">Objetivo</span><h2>{p.objetivo}</h2><p>{p.descricao||'Complete o mapeamento para enriquecer a descrição deste processo.'}</p><div className="pc-journey"><div><Circle/><small>Evento inicial</small><b>{p.eventoInicial}</b></div><i/><div><CheckCircle2/><small>Resultado esperado</small><b>{p.resultadoEsperado}</b></div></div></article><aside className="pc-panel pc-completeness"><span className="pc-kicker">Qualidade do mapeamento</span><strong>{Math.round((perguntas.filter(([k])=>entrevista[k]).length/perguntas.length)*100)}%</strong><div><i style={{width:`${(perguntas.filter(([k])=>entrevista[k]).length/perguntas.length)*100}%`}}/></div><p>{perguntas.filter(([k])=>entrevista[k]).length} de {perguntas.length} perguntas respondidas</p><BotaoPrimario onClick={()=>setAba('entrevista')}>Continuar entrevista</BotaoPrimario></aside></div>}
      {aba==='entrevista'&&<div className="pc-interview"><aside><span className="pc-kicker">Roteiro guiado</span><h2>Entrevista do processo</h2><p>Registre como o trabalho realmente acontece. O rascunho é salvo automaticamente.</p><div className="pc-interview-progress"><b>{perguntas.filter(([k])=>entrevista[k]).length}/{perguntas.length}</b><span>respondidas</span></div></aside><div className="pc-question-list">{perguntas.map(([k,pergunta],i)=><label className={entrevista[k]?'respondida':''} key={k}><span><i>{i+1}</i>{pergunta}{Boolean(entrevista[k])&&<CheckCircle2 size={17}/>}</span><textarea disabled={travado} value={String(entrevista[k]??'')} onChange={e=>mudarEntrevista(k,e.target.value)} placeholder="Registre a resposta, exemplos e exceções…"/></label>)}</div></div>}
      {aba==='fluxo'&&<EditorFluxo codigo={p.codigo} nome={p.nome} etapas={etapas} onChange={mudarEtapas} travado={travado}/>} 
      {aba==='manual'&&<div className="pc-manual-grid"><article className="pc-panel"><span className="pc-kicker">Manual operacional vivo</span><h2>{p.nome}</h2><div className="pc-field"><label>Resumo para o colaborador</label><textarea disabled={travado} value={String(manual.resumo??'')} onChange={e=>mudarManual('resumo',e.target.value)} placeholder="Explique este procedimento de forma simples…"/></div><div className="pc-field"><label>Cuidados e regras importantes</label><textarea disabled={travado} value={String(manual.cuidados??'')} onChange={e=>mudarManual('cuidados',e.target.value)} placeholder="O que não pode ser esquecido?"/></div><div className="pc-field"><label>Em caso de dúvida</label><input disabled={travado} value={String(manual.suporte??'')} onChange={e=>mudarManual('suporte',e.target.value)} placeholder="Pessoa ou canal responsável"/></div></article><aside className="pc-panel pc-manual-preview"><span className="pc-kicker">Prévia</span><h3>{p.nome}</h3><p>{String(manual.resumo??p.objetivo)}</p><ol>{etapas.map(e=><li key={e.id}>{e.nome}</li>)}</ol>{Boolean(manual.cuidados)&&<div className="pc-callout"><b>Atenção</b><p>{String(manual.cuidados)}</p></div>}</aside></div>}
      {aba==='validacao'&&<div className="pc-validation"><article className="pc-panel"><ShieldCheck size={28}/><span className="pc-kicker">Governança</span><h2>Validação da liderança</h2><p>Depois do envio, a liderança pode aprovar ou devolver o processo com uma justificativa. Versões aprovadas ficam protegidas.</p><div className="pc-validation-actions">{!travado&&p.situacao!=='aguardando_validacao'&&<BotaoPrimario onClick={()=>transicao.mutate({acao:'enviar_validacao'})}><Send size={15}/> Enviar para validação</BotaoPrimario>}{p.situacao==='aguardando_validacao'&&<><BotaoPrimario onClick={()=>transicao.mutate({acao:'aprovar'})}><CheckCircle2 size={15}/> Aprovar versão</BotaoPrimario><BotaoPrimario variante="secundario" onClick={()=>{const m=prompt('Qual ajuste precisa ser feito?');if(m)transicao.mutate({acao:'solicitar_ajustes',motivo:m})}}><XCircle size={15}/> Solicitar ajustes</BotaoPrimario></>}</div></article></div>}
      {aba==='historico'&&<div className="pc-panel"><span className="pc-kicker">Rastreabilidade</span><h2>Histórico de alterações</h2><div className="pc-timeline">{(p.auditoria??[]).map(a=><div key={a.id}><i/><div><b>{rotuloProcesso(a.acao)}</b><span>{new Date(a.criadaEm).toLocaleString('pt-BR')} · versão {a.versao??p.versaoAtual}</span>{a.motivo&&<p>{a.motivo}</p>}</div></div>)}{!(p.auditoria??[]).length&&<p>Nenhuma alteração registrada.</p>}</div></div>}
    </section>
  </main>;
}
