import type { PatientFormValues } from '../types/patient-form';

export const PATIENT_FORM_INITIAL_VALUES: PatientFormValues = {
  name: '',
  gender: 'male',
  birthDate: '',
  cpf: '',
  rg: '',
  phone: '',
  referralOriginId: '',
  referralOriginSystemKey: '',
  referredByPatientId: '',
  referredByPatientName: '',
  referredByMemberId: '',
  referredByMemberName: '',
  referredByExternalProfessionalId: '',
  referredByExternalProfessionalName: '',
  categoryId: '',
  guardianName: '',
  guardianBirthDate: '',
  guardianCpf: '',
  guardianPhone: '',
  guardianNotes: '',
  email: '',
  landlinePhone: '',
  medicalRecordNumber: '',
  profession: '',
  socialNetwork: '',
  planId: '',
  planNumber: '',
  planHolderName: '',
  planHolderCpf: '',
  zipCode: '',
  street: '',
  streetNumber: '',
  complement: '',
  neighborhood: '',
  city: '',
  state: '',
};
