-- ============================================================================
-- Identidade das tabelas de carga que usam chave substituta
--
-- Mesma origem do problema anterior: o export veio pelo PostgREST, que devolve
-- dados e não DDL, então nenhuma sequence sobreviveu. Nas tabelas cuja chave
-- vem da origem (fato_loja_cupom.cupom_id, fato_loja_estoque.produto_id,
-- fato_loja_item/pagamento.cupom_id+seq_item) isso não importa: o ETL manda o
-- valor. Mas estas três têm `id` substituto, que ninguém preenche — o INSERT
-- morria com 23502 (null value in column "id").
--
-- IDENTITY começa do maior id existente para não colidir com o que veio no
-- dump. GENERATED BY DEFAULT (e não ALWAYS) para que uma carga futura que
-- traga o id explícito continue funcionando.
-- ============================================================================

DO $$
DECLARE
  t text;
  proximo bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY['fato_loja_curso', 'fato_loja_receita_extra', 'fato_avaliacao_evento']
  LOOP
    -- Só age se a coluna ainda não for identidade: a migration precisa poder
    -- rodar de novo sem erro.
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = t
         AND column_name = 'id' AND is_identity = 'NO' AND column_default IS NULL
    ) THEN
      EXECUTE format('SELECT coalesce(max(id), 0) + 1 FROM public.%I', t) INTO proximo;
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
        t, proximo);
      RAISE NOTICE 'identidade criada em %.id começando em %', t, proximo;
    END IF;
  END LOOP;
END $$;
