import type { StockProduct, Supplier } from "./types";

/** Profissionais fictícios usados apenas no mock de movimentações de estoque. */
export const MOCK_STOCK_MEMBERS = [
  { id: "prof-mock-1", name: "Dr. Leonardo Ramos" },
  { id: "prof-mock-2", name: "Dra. Maria Silva" },
  { id: "prof-mock-3", name: "Dr. Carlos Santos" },
  { id: "prof-mock-4", name: "Dra. Ana Oliveira" },
] as const;

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: "mock-1", name: "MedSupply", phone: "(73) 99999-0001", email: "contato@medsupply.com", createdAt: "2024-01-02T10:00:00.000Z" },
  { id: "mock-2", name: "DentalPro", phone: "(73) 99999-0002", email: "vendas@dentalpro.com", createdAt: "2024-01-03T10:00:00.000Z" },
  { id: "mock-3", name: "3M Dental", phone: null, email: null, createdAt: "2024-01-04T10:00:00.000Z" },
  { id: "mock-4", name: "DFL", phone: "(73) 99999-0004", email: null, createdAt: "2024-01-05T10:00:00.000Z" },
  { id: "mock-5", name: "Ethicon", phone: null, email: "sac@ethicon.com", createdAt: "2024-01-06T10:00:00.000Z" },
  { id: "mock-6", name: "KG Sorensen", phone: "(73) 99999-0006", email: null, createdAt: "2024-01-07T10:00:00.000Z" },
];

export const MOCK_STOCK_PRODUCTS: StockProduct[] = [
  {
    id: "1",
    name: "Luvas de Procedimento M",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Luvas",
    category: "Descartáveis",
    sku: "LUV-M-001",
    supplierId: "mock-1",
    supplier: { id: "mock-1", name: "MedSupply" },
    quantity: 500,
    minQuantity: 100,
    unitCost: 0.45,
    activeValue: 225,
    status: "in_stock",
  },
  {
    id: "2",
    name: "Agulha Gengival 30G",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Agulha",
    category: "Anestésicos",
    sku: "AGN-30G-002",
    supplierId: "mock-2",
    supplier: { id: "mock-2", name: "DentalPro" },
    quantity: 45,
    minQuantity: 50,
    unitCost: 1.2,
    activeValue: 54,
    status: "low_stock",
  },
  {
    id: "3",
    name: "Resina Composta A2",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Resina",
    category: "Restauradores",
    sku: "RES-A2-003",
    supplierId: "mock-3",
    supplier: { id: "mock-3", name: "3M Dental" },
    quantity: 0,
    minQuantity: 10,
    unitCost: 89.9,
    activeValue: 0,
    status: "out_of_stock",
  },
  {
    id: "4",
    name: "Sugador Descartável",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Sugador",
    category: "Descartáveis",
    sku: "SUG-D-004",
    supplierId: "mock-1",
    supplier: { id: "mock-1", name: "MedSupply" },
    quantity: 1200,
    minQuantity: 200,
    unitCost: 0.15,
    activeValue: 180,
    status: "in_stock",
  },
  {
    id: "5",
    name: "Anestésico Lidocaína 2%",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Lidoca",
    category: "Anestésicos",
    sku: "ANE-LID-005",
    supplierId: "mock-4",
    supplier: { id: "mock-4", name: "DFL" },
    quantity: 8,
    minQuantity: 20,
    unitCost: 12.5,
    activeValue: 100,
    status: "low_stock",
  },
  {
    id: "6",
    name: "Fio de Sutura 4-0",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Sutura",
    category: "Cirúrgicos",
    sku: "SUT-40-006",
    supplierId: "mock-5",
    supplier: { id: "mock-5", name: "Ethicon" },
    quantity: 0,
    minQuantity: 15,
    unitCost: 25.0,
    activeValue: 0,
    status: "out_of_stock",
  },
  {
    id: "7",
    name: "Broca Diamantada 1012",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Broca",
    category: "Instrumentais",
    sku: "BRC-1012-007",
    supplierId: "mock-6",
    supplier: { id: "mock-6", name: "KG Sorensen" },
    quantity: 30,
    minQuantity: 10,
    unitCost: 8.9,
    activeValue: 267,
    status: "in_stock",
  },
  {
    id: "8",
    name: "Máscara Tripla Camada",
    photoUrl: "https://placehold.co/80x80/e2e8f0/64748b?text=Mascara",
    category: "Descartáveis",
    sku: "MSK-TC-008",
    supplierId: "mock-1",
    supplier: { id: "mock-1", name: "MedSupply" },
    quantity: 800,
    minQuantity: 100,
    unitCost: 0.35,
    activeValue: 280,
    status: "in_stock",
  },
];
