import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { UsuarioLogado } from '../../common/decorators/usuario.decorator';
import { AcaoCompraDto, CotacaoDto, CriarSolicitacaoDto, EmitirPedidoDto, EscolherCotacaoDto, EstoqueItemDto, ReceberDto } from './compras.dto';

const operador = (u: UsuarioLogado) => u.papel === 'admin' || u.permissoes.includes('compras.operar');
const aprovador = (u: UsuarioLogado) => u.papel === 'admin' || u.permissoes.includes('compras.aprovar');
const inclusoes = { itens: true, cotacoes: { orderBy: { valorTotal: 'asc' as const } }, pedidos: { orderBy: { criadoEm: 'desc' as const } }, recebimentos: { orderBy: { criadoEm: 'desc' as const } }, historico: { orderBy: { criadoEm: 'desc' as const } } };
const jsonSeguro = <T>(valor:T):T => JSON.parse(JSON.stringify(valor,(_chave,item)=>typeof item==='bigint'?item.toString():item));

@Injectable()
export class ComprasService {
  constructor(private readonly prisma: PrismaService) {}

  private podeVer(u: UsuarioLogado, s: { solicitanteId: string }) { return operador(u) || aprovador(u) || s.solicitanteId === u.id; }
  async listar(u: UsuarioLogado, escopo = 'todas', situacao?: string, busca?: string) {
    const restrito = (!operador(u) && !aprovador(u)) || escopo === 'minhas';
    if (escopo === 'aprovacoes' && !aprovador(u)) throw new ForbiddenException('Esta fila exige permissão de aprovação.');
    return jsonSeguro(await this.prisma.compraSolicitacao.findMany({ where: { ...(restrito ? { solicitanteId: u.id } : {}), ...(escopo === 'aprovacoes' ? { situacao: 'aguardando_aprovacao' } : {}), ...(situacao ? { situacao } : {}), ...(busca ? { OR: [{ protocolo: { contains: busca, mode: 'insensitive' } }, { titulo: { contains: busca, mode: 'insensitive' } }] } : {}) }, include: { itens: true, cotacoes: true, pedidos: true }, orderBy: [{ dataNecessaria: 'asc' }, { criadoEm: 'desc' }], take: 200 }));
  }
  async indicadores(u: UsuarioLogado) { const where = !operador(u) && !aprovador(u) ? { solicitanteId: u.id } : {}; const g = await this.prisma.compraSolicitacao.groupBy({ where, by: ['situacao'], _count: true }); return { total: g.reduce((s, x) => s + x._count, 0), porSituacao: Object.fromEntries(g.map(x => [x.situacao, x._count])) }; }
  async obter(id: string, u: UsuarioLogado) { const s = await this.prisma.compraSolicitacao.findUnique({ where: { id }, include: inclusoes }); if (!s) throw new NotFoundException('Solicitação não encontrada.'); if (!this.podeVer(u, s)) throw new ForbiddenException('Você não pode consultar esta solicitação.'); return jsonSeguro(s); }

  async contextoFormulario(u: UsuarioLogado) {
    const [usuario, unidades, setores, eventos, cursos] = await Promise.all([
      this.prisma.usuario.findUnique({ where:{id:u.id}, select:{id:true,nome:true,setor:true} }),
      this.prisma.usuarioUnidadeCompra.findMany({ where:{usuarioId:u.id,unidade:{ativa:true}}, include:{unidade:true}, orderBy:{principal:'desc'} }),
      this.prisma.setorCompra.findMany({ where:{ativo:true,...(!operador(u)?{slug:{in:u.setores}}:{})}, orderBy:{nome:'asc'} }),
      this.prisma.dimEvento.findMany({ where:{nomeEvento:{not:null}},select:{eventoId:true,nomeEvento:true},orderBy:{dataInicio:'desc'},take:30 }),
      this.prisma.dimCurso.findMany({ where:{nomeCurso:{not:null}},select:{cursoId:true,nomeCurso:true},orderBy:{nomeCurso:'asc'},take:30 }),
    ]);
    const principal=setores.find(s=>s.slug===usuario?.setor)??setores[0];
    return {solicitante:usuario,unidades:unidades.map(x=>({...x.unidade,principal:x.principal})),setores,setorPrincipalId:principal?.id,unidadePrincipalId:unidades[0]?.unidadeId,podeAlterarUnidade:operador(u)||unidades.length>1,podeAlterarSetor:operador(u)||setores.length>1,eventos:[...eventos.map(e=>({id:`evento:${e.eventoId}`,nome:e.nomeEvento,tipo:'Evento'})),...cursos.map(c=>({id:`curso:${c.cursoId}`,nome:c.nomeCurso,tipo:'Curso'}))]};
  }

  async criar(dto: CriarSolicitacaoDto, u: UsuarioLogado) {
    if (!dto.itens?.length) throw new BadRequestException('Inclua pelo menos um item.');
    const [vinculo,setor]=await Promise.all([this.prisma.usuarioUnidadeCompra.findUnique({where:{usuarioId_unidadeId:{usuarioId:u.id,unidadeId:dto.unidadeId}},include:{unidade:true}}),this.prisma.setorCompra.findUnique({where:{id:dto.setorId}})]);
    if(!vinculo)throw new ForbiddenException('Unidade não autorizada para este usuário.');
    if(!setor||(!operador(u)&&!u.setores.includes(setor.slug)))throw new ForbiddenException('Setor não autorizado para este usuário.');
    const ano = new Date().getUTCFullYear();
    return this.prisma.$transaction(async tx => {
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(${ano})`;
      const ultimo = await tx.compraSolicitacao.findFirst({ where: { protocolo: { startsWith: `SC-${ano}-` } }, orderBy: { protocolo: 'desc' }, select: { protocolo: true } });
      const sequencia = String(Number(ultimo?.protocolo.split('-').at(-1) ?? 0) + 1).padStart(5, '0');
      const s = await tx.compraSolicitacao.create({ data: { protocolo: `SC-${ano}-${sequencia}`, titulo: dto.titulo, tipo: dto.tipo, justificativa: dto.justificativa, setor:setor.slug,setorId:setor.id,unidade:vinculo.unidade.nome,unidadeId:vinculo.unidade.id, centroCusto: dto.centroCusto, projeto: dto.projeto, dataNecessaria: dto.dataNecessaria ? new Date(dto.dataNecessaria) : undefined, observacoes: dto.observacoes, prioridade: dto.prioridade ?? 'normal', situacao: 'aguardando_analise', solicitanteId: u.id, itens: { create: dto.itens.map(i => ({ ...i, produtoId: i.produtoId ? BigInt(i.produtoId) : undefined,situacao:i.produtoId?'pendente':'nao_cadastrado',finalidade:undefined })) }, historico: { create: [{ usuarioId: u.id, acao: 'criada', situacaoNova: 'rascunho' }, { usuarioId: u.id, acao: 'enviada', situacaoAnterior: 'rascunho', situacaoNova: 'aguardando_analise' }] } }, include: { itens: true } });
      const responsaveis = await tx.usuario.findMany({ where: { ativo: true, OR: [{ papel: 'admin' }, { perfilAcesso: { permissoes: { has: 'compras.operar' } } }] }, select: { id: true } });
      await tx.notificacao.createMany({ data: responsaveis.filter(x => x.id !== u.id).map(x => ({ usuarioId: x.id, titulo: 'Nova solicitação de compra', mensagem: `${s.protocolo} · ${s.titulo}`, tipo: 'info', categoria: 'compras', href: `/compras/${s.id}`, criadaPor: u.id })) });
      return jsonSeguro(s);
    });
  }
  async produtos(busca = '') {
    const produtos = await this.prisma.fatoLojaEstoque.findMany({ where: busca ? { OR: [{ descricao: { contains: busca, mode: 'insensitive' } }, { codigo: { contains: busca, mode: 'insensitive' } }] } : {}, orderBy: { descricao: 'asc' }, take: 30 });
    return produtos.map((produto) => ({ ...produto, produtoId: produto.produtoId.toString() }));
  }

  async estoque(id: string, itemId: string, dto: EstoqueItemDto, u: UsuarioLogado) {
    if (!operador(u)) throw new ForbiddenException(); const s = await this.obter(id, u); if (s.situacao !== 'verificacao_estoque') throw new BadRequestException('A solicitação não está em verificação de estoque.');
    const item = s.itens.find(i => i.id === itemId); if (!item) throw new NotFoundException('Item não encontrado.'); const produtoId = dto.produtoId ? BigInt(dto.produtoId) : item.produtoId; if (!produtoId && dto.quantidadeReservada > 0) throw new BadRequestException('Selecione um produto real do estoque.');
    const produto = produtoId ? await this.prisma.fatoLojaEstoque.findUnique({ where: { produtoId } }) : null; const disponivel = Number(produto?.saldo ?? 0) - Number(produto?.reservado ?? 0); if (dto.quantidadeReservada > disponivel || dto.quantidadeReservada > Number(item.quantidade)) throw new BadRequestException('Reserva maior que o saldo disponível ou solicitado.');
    return this.prisma.$transaction(async tx => { const atualizado = await tx.compraItem.update({ where: { id: itemId }, data: { produtoId, estoqueDisponivel: Math.max(0, disponivel), quantidadeReservada: dto.quantidadeReservada, situacao: dto.quantidadeReservada >= Number(item.quantidade) ? 'reservado' : 'comprar' } }); if (produtoId && dto.quantidadeReservada > 0) { await tx.fatoLojaEstoque.update({ where: { produtoId }, data: { reservado: { increment: new Prisma.Decimal(dto.quantidadeReservada) } } }); await tx.compraMovimentoEstoque.create({ data: { solicitacaoId: id, itemId, produtoId, tipo: 'reserva', quantidade: dto.quantidadeReservada, usuarioId: u.id } }); } await this.hist(tx, id, u, 'estoque_verificado', s.situacao, s.situacao, `${item.descricao}: reservado ${dto.quantidadeReservada}`); return atualizado; });
  }
  async cotar(id: string, dto: CotacaoDto, u: UsuarioLogado) { if (!operador(u)) throw new ForbiddenException(); const s = await this.obter(id, u); if (s.situacao !== 'em_cotacao') throw new BadRequestException('A solicitação não está em cotação.'); const { validadeProposta, ...rest } = dto; return this.prisma.compraCotacao.create({ data: { solicitacaoId: id, ...rest, validadeProposta: validadeProposta ? new Date(validadeProposta) : undefined, criadaPor: u.id } }); }
  async escolherCotacao(id: string, cotacaoId: string, dto: EscolherCotacaoDto, u: UsuarioLogado) { if (!operador(u)) throw new ForbiddenException(); const s = await this.obter(id, u); if (s.situacao !== 'em_cotacao') throw new BadRequestException('A solicitação não está em cotação.'); const alvo = s.cotacoes.find(c => c.id === cotacaoId); if (!alvo) throw new NotFoundException('Cotação não encontrada.'); const menor = Math.min(...s.cotacoes.map(c => Number(c.valorTotal))); if (Number(alvo.valorTotal) > menor && !dto.justificativa?.trim()) throw new BadRequestException('Justifique a escolha que não possui o menor preço.'); return this.prisma.$transaction(async tx => { await tx.compraCotacao.updateMany({ where: { solicitacaoId: id }, data: { escolhida: false } }); const c = await tx.compraCotacao.update({ where: { id: cotacaoId }, data: { escolhida: true, criterioEscolha: dto.criterio, justificativaEscolha: dto.justificativa, escolhidaPor: u.id, escolhidaEm: new Date() } }); await this.hist(tx, id, u, 'cotacao_escolhida', s.situacao, s.situacao, `${c.fornecedor} · ${dto.criterio}${dto.justificativa ? ` · ${dto.justificativa}` : ''}`); return c; }); }

  async emitirPedido(id: string, dto: EmitirPedidoDto, u: UsuarioLogado) { if (!operador(u)) throw new ForbiddenException(); const s = await this.obter(id, u); if (s.situacao !== 'aprovada') throw new BadRequestException('A solicitação precisa estar aprovada.'); const c = s.cotacoes.find(x => x.escolhida); if (!c) throw new BadRequestException('Cotação escolhida ausente.'); return this.prisma.$transaction(async tx => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(92845)`; const total = await tx.compraPedido.count(); const p = await tx.compraPedido.create({ data: { solicitacaoId: id, cotacaoId: c.id, numero: `PC-${new Date().getUTCFullYear()}-${String(total + 1).padStart(5, '0')}`, fornecedor: c.fornecedor, valorTotal: c.valorTotal, condicaoPagamento: c.condicaoPagamento, previsaoEntrega: dto.previsaoEntrega ? new Date(dto.previsaoEntrega) : undefined, criadoPor: u.id } }); await tx.compraSolicitacao.update({ where: { id }, data: { situacao: 'pedido_emitido', pedidoNumero: p.numero, previsaoEntrega: p.previsaoEntrega, revisao: { increment: 1 } } }); await this.hist(tx, id, u, 'pedido_emitido', 'aprovada', 'pedido_emitido', p.numero); return p; }); }
  async receber(id: string, dto: ReceberDto, u: UsuarioLogado) { if (!operador(u)) throw new ForbiddenException(); const s = await this.obter(id, u); if (!['aguardando_entrega', 'recebida_parcialmente'].includes(s.situacao)) throw new BadRequestException('A solicitação não está aguardando recebimento.'); return this.prisma.$transaction(async tx => { for (const r of dto.itens) { const item = s.itens.find(i => i.id === r.itemId); if (!item) throw new BadRequestException('Item inválido.'); if (Number(item.quantidadeRecebida) + r.quantidade > Number(item.quantidade) - Number(item.quantidadeReservada)) throw new BadRequestException(`Quantidade recebida excede o saldo de ${item.descricao}.`); await tx.compraItem.update({ where: { id: item.id }, data: { quantidadeRecebida: { increment: r.quantidade } } }); } const rec = await tx.compraRecebimento.create({ data: { solicitacaoId: id, pedidoId: s.pedidos[0]?.id, notaFiscal: dto.notaFiscal, observacoes: dto.observacoes, divergencia: dto.divergencia, itens: dto.itens as unknown as Prisma.InputJsonValue, recebidoPor: u.id } }); const itens = await tx.compraItem.findMany({ where: { solicitacaoId: id } }); const completo = itens.every(i => Number(i.quantidadeRecebida) + Number(i.quantidadeReservada) >= Number(i.quantidade)); const nova = completo ? 'recebida' : 'recebida_parcialmente'; await tx.compraSolicitacao.update({ where: { id }, data: { situacao: nova, recebidoEm: completo ? new Date() : undefined, revisao: { increment: 1 } } }); await this.hist(tx, id, u, completo ? 'recebimento_total' : 'recebimento_parcial', s.situacao, nova, dto.observacoes); return rec; }); }

  async agir(id: string, dto: AcaoCompraDto, u: UsuarioLogado) {
    const s = await this.obter(id, u);
    const mapa: Record<string, [string[], string]> = { assumir: [['aguardando_analise'], 'aguardando_analise'], solicitar_complementacao: [['aguardando_analise'], 'aguardando_complementacao'], complementar: [['aguardando_complementacao'], 'aguardando_analise'], analisar: [['aguardando_analise'], s.tipo === 'servico' ? 'em_cotacao' : 'verificacao_estoque'], iniciar_cotacao: [['verificacao_estoque'], 'em_cotacao'], atender_estoque: [['verificacao_estoque'], 'atendida_estoque'], submeter_aprovacao: [['em_cotacao'], 'aguardando_aprovacao'], aprovar: [['aguardando_aprovacao'], 'aprovada'], reprovar: [['aguardando_aprovacao'], 'reprovada'], solicitar_ajuste: [['aguardando_aprovacao'], 'ajustes_solicitados'], reenviar_aprovacao: [['ajustes_solicitados'], 'aguardando_aprovacao'], enviar_pedido: [['pedido_emitido'], 'aguardando_entrega'], preparar_entrega: [['recebida', 'atendida_estoque'], 'pronta_entrega'], entregar: [['pronta_entrega'], 'entregue'], confirmar_recebimento: [['entregue'], 'encerrada'], cancelar: [['rascunho', 'aguardando_analise', 'aguardando_complementacao', 'em_cotacao'], 'cancelada'], comentar: [[s.situacao], s.situacao] };
    const t = mapa[dto.acao]; if (!t || !t[0].includes(s.situacao)) throw new BadRequestException(`A ação ${dto.acao} não é permitida em ${s.situacao}.`);
    if (['aprovar', 'reprovar', 'solicitar_ajuste'].includes(dto.acao) && !aprovador(u)) throw new ForbiddenException('Esta ação exige permissão de aprovação.'); if (['assumir', 'analisar', 'iniciar_cotacao', 'atender_estoque', 'submeter_aprovacao', 'reenviar_aprovacao', 'enviar_pedido', 'preparar_entrega', 'entregar'].includes(dto.acao) && !operador(u)) throw new ForbiddenException('Esta ação exige permissão de Compras.'); if (['solicitar_complementacao', 'reprovar', 'solicitar_ajuste', 'cancelar', 'comentar'].includes(dto.acao) && !dto.comentario?.trim()) throw new BadRequestException('Informe um comentário ou justificativa.'); if (dto.acao === 'submeter_aprovacao' && !s.cotacoes.some(c => c.escolhida)) throw new BadRequestException('Escolha uma cotação antes de encaminhar.'); if (['complementar', 'confirmar_recebimento', 'cancelar'].includes(dto.acao) && s.solicitanteId !== u.id && !operador(u)) throw new ForbiddenException();
    return this.prisma.$transaction(async tx => { await tx.compraSolicitacao.update({ where: { id }, data: { situacao: t[1], ...(dto.acao === 'assumir' ? { responsavelId: u.id } : {}), ...(dto.acao === 'aprovar' ? { aprovadorId: u.id, decisao: 'aprovada' } : {}), ...(dto.acao === 'reprovar' ? { aprovadorId: u.id, decisao: 'reprovada', motivoDecisao: dto.comentario } : {}), ...(dto.acao === 'confirmar_recebimento' ? { encerradoEm: new Date() } : {}), revisao: { increment: 1 } } }); await this.hist(tx, id, u, dto.acao, s.situacao, t[1], dto.comentario); return tx.compraSolicitacao.findUnique({ where: { id }, include: inclusoes }); });
  }
  private hist(tx: Prisma.TransactionClient, id: string, u: UsuarioLogado, acao: string, anterior: string, nova: string, comentario?: string) { return tx.compraHistorico.create({ data: { solicitacaoId: id, usuarioId: u.id, acao, situacaoAnterior: anterior, situacaoNova: nova, comentario } }); }
}
