/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.AssinaturaApi
import com.citybox.api.models.CancelSubscription200Response
import com.citybox.api.models.CancelSubscriptionRequest
import com.citybox.api.models.GetSubscription200Response

class AssinaturaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AssinaturaApi
        //val apiInstance = AssinaturaApi()

        // to test cancelSubscription
        should("test cancelSubscription") {
            // uncomment below to test cancelSubscription
            //val cancelSubscriptionRequest : CancelSubscriptionRequest =  // CancelSubscriptionRequest | 
            //val result : CancelSubscription200Response = apiInstance.cancelSubscription(cancelSubscriptionRequest)
            //result shouldBe ("TODO")
        }

        // to test getSubscription
        should("test getSubscription") {
            // uncomment below to test getSubscription
            //val result : GetSubscription200Response = apiInstance.getSubscription()
            //result shouldBe ("TODO")
        }

    }
}
