/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.AuthApi
import com.citybox.api.models.AuthEnvelope
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.ForgotPassword200Response
import com.citybox.api.models.ForgotPasswordRequest
import com.citybox.api.models.LoginGoogleRequest
import com.citybox.api.models.LoginRequest
import com.citybox.api.models.LogoutRequest
import com.citybox.api.models.MessageEnvelope
import com.citybox.api.models.OnboardingEnvelope
import com.citybox.api.models.OnboardingPostLoginRequest
import com.citybox.api.models.OnboardingPreLoginRequest
import com.citybox.api.models.RefreshToken200Response
import com.citybox.api.models.RegisterRequest
import com.citybox.api.models.ResetPasswordRequest
import com.citybox.api.models.SessionEnvelope

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test forgotPassword
        should("test forgotPassword") {
            // uncomment below to test forgotPassword
            //val forgotPasswordRequest : ForgotPasswordRequest =  // ForgotPasswordRequest | 
            //val result : ForgotPassword200Response = apiInstance.forgotPassword(forgotPasswordRequest)
            //result shouldBe ("TODO")
        }

        // to test getSession
        should("test getSession") {
            // uncomment below to test getSession
            //val result : SessionEnvelope = apiInstance.getSession()
            //result shouldBe ("TODO")
        }

        // to test login
        should("test login") {
            // uncomment below to test login
            //val loginRequest : LoginRequest = {"account":"camila@email.com","password":"123456","hasSeenOnboarding":true} // LoginRequest | 
            //val result : AuthEnvelope = apiInstance.login(loginRequest)
            //result shouldBe ("TODO")
        }

        // to test loginGoogle
        should("test loginGoogle") {
            // uncomment below to test loginGoogle
            //val loginGoogleRequest : LoginGoogleRequest =  // LoginGoogleRequest | 
            //val result : AuthEnvelope = apiInstance.loginGoogle(loginGoogleRequest)
            //result shouldBe ("TODO")
        }

        // to test logout
        should("test logout") {
            // uncomment below to test logout
            //val logoutRequest : LogoutRequest =  // LogoutRequest | 
            //apiInstance.logout(logoutRequest)
        }

        // to test onboardingPostLogin
        should("test onboardingPostLogin") {
            // uncomment below to test onboardingPostLogin
            //val onboardingPostLoginRequest : OnboardingPostLoginRequest =  // OnboardingPostLoginRequest | 
            //val result : OnboardingEnvelope = apiInstance.onboardingPostLogin(onboardingPostLoginRequest)
            //result shouldBe ("TODO")
        }

        // to test onboardingPreLogin
        should("test onboardingPreLogin") {
            // uncomment below to test onboardingPreLogin
            //val onboardingPreLoginRequest : OnboardingPreLoginRequest =  // OnboardingPreLoginRequest | 
            //val result : OnboardingEnvelope = apiInstance.onboardingPreLogin(onboardingPreLoginRequest)
            //result shouldBe ("TODO")
        }

        // to test refreshToken
        should("test refreshToken") {
            // uncomment below to test refreshToken
            //val logoutRequest : LogoutRequest =  // LogoutRequest | 
            //val result : RefreshToken200Response = apiInstance.refreshToken(logoutRequest)
            //result shouldBe ("TODO")
        }

        // to test register
        should("test register") {
            // uncomment below to test register
            //val registerRequest : RegisterRequest =  // RegisterRequest | 
            //val result : AuthEnvelope = apiInstance.register(registerRequest)
            //result shouldBe ("TODO")
        }

        // to test resetPassword
        should("test resetPassword") {
            // uncomment below to test resetPassword
            //val resetPasswordRequest : ResetPasswordRequest =  // ResetPasswordRequest | 
            //val result : MessageEnvelope = apiInstance.resetPassword(resetPasswordRequest)
            //result shouldBe ("TODO")
        }

    }
}
