/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.CarrinhoApi
import com.citybox.api.models.AddCartItemRequest
import com.citybox.api.models.ApplyCartCoupon200Response
import com.citybox.api.models.ApplyCartCouponRequest
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetCart200Response
import com.citybox.api.models.UpdateCartItemRequest

class CarrinhoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CarrinhoApi
        //val apiInstance = CarrinhoApi()

        // to test addCartItem
        should("test addCartItem") {
            // uncomment below to test addCartItem
            //val addCartItemRequest : AddCartItemRequest =  // AddCartItemRequest | 
            //val result : GetCart200Response = apiInstance.addCartItem(addCartItemRequest)
            //result shouldBe ("TODO")
        }

        // to test applyCartCoupon
        should("test applyCartCoupon") {
            // uncomment below to test applyCartCoupon
            //val applyCartCouponRequest : ApplyCartCouponRequest =  // ApplyCartCouponRequest | 
            //val result : ApplyCartCoupon200Response = apiInstance.applyCartCoupon(applyCartCouponRequest)
            //result shouldBe ("TODO")
        }

        // to test clearCart
        should("test clearCart") {
            // uncomment below to test clearCart
            //apiInstance.clearCart()
        }

        // to test getCart
        should("test getCart") {
            // uncomment below to test getCart
            //val result : GetCart200Response = apiInstance.getCart()
            //result shouldBe ("TODO")
        }

        // to test removeCartItem
        should("test removeCartItem") {
            // uncomment below to test removeCartItem
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val result : GetCart200Response = apiInstance.removeCartItem(productId)
            //result shouldBe ("TODO")
        }

        // to test updateCartItem
        should("test updateCartItem") {
            // uncomment below to test updateCartItem
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val updateCartItemRequest : UpdateCartItemRequest =  // UpdateCartItemRequest | 
            //val result : GetCart200Response = apiInstance.updateCartItem(productId, updateCartItemRequest)
            //result shouldBe ("TODO")
        }

    }
}
