/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.CatalogoApi
import com.citybox.api.models.AddReviewPhoto201Response
import com.citybox.api.models.AddSearchHistoryRequest
import com.citybox.api.models.CreateReview201Response
import com.citybox.api.models.CreateReviewRequest
import com.citybox.api.models.CreateReviewRequest1
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetCategoryProducts200Response
import com.citybox.api.models.GetFiltersMetadata200Response
import com.citybox.api.models.GetHome200Response
import com.citybox.api.models.GetProduct200Response
import com.citybox.api.models.GetReviews200Response
import com.citybox.api.models.ListCategories200Response
import com.citybox.api.models.SearchHistoryEnvelope
import com.citybox.api.models.SearchProducts200Response
import com.citybox.api.models.SearchSuggestions200Response
import com.citybox.api.models.SortOption

class CatalogoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogoApi
        //val apiInstance = CatalogoApi()

        // to test addReviewPhoto
        should("test addReviewPhoto") {
            // uncomment below to test addReviewPhoto
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val reviewId : kotlin.String = reviewId_example // kotlin.String | 
            //val file : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : AddReviewPhoto201Response = apiInstance.addReviewPhoto(productId, reviewId, file)
            //result shouldBe ("TODO")
        }

        // to test addSearchHistory
        should("test addSearchHistory") {
            // uncomment below to test addSearchHistory
            //val addSearchHistoryRequest : AddSearchHistoryRequest =  // AddSearchHistoryRequest | 
            //val result : SearchHistoryEnvelope = apiInstance.addSearchHistory(addSearchHistoryRequest)
            //result shouldBe ("TODO")
        }

        // to test clearSearchHistory
        should("test clearSearchHistory") {
            // uncomment below to test clearSearchHistory
            //apiInstance.clearSearchHistory()
        }

        // to test createReview
        should("test createReview") {
            // uncomment below to test createReview
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val createReviewRequest : CreateReviewRequest =  // CreateReviewRequest | 
            //val result : CreateReview201Response = apiInstance.createReview(productId, createReviewRequest)
            //result shouldBe ("TODO")
        }

        // to test getCategoryProducts
        should("test getCategoryProducts") {
            // uncomment below to test getCategoryProducts
            //val categoryId : kotlin.String = tecnologia // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : GetCategoryProducts200Response = apiInstance.getCategoryProducts(categoryId, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test getFiltersMetadata
        should("test getFiltersMetadata") {
            // uncomment below to test getFiltersMetadata
            //val result : GetFiltersMetadata200Response = apiInstance.getFiltersMetadata()
            //result shouldBe ("TODO")
        }

        // to test getHome
        should("test getHome") {
            // uncomment below to test getHome
            //val result : GetHome200Response = apiInstance.getHome()
            //result shouldBe ("TODO")
        }

        // to test getProduct
        should("test getProduct") {
            // uncomment below to test getProduct
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val result : GetProduct200Response = apiInstance.getProduct(productId)
            //result shouldBe ("TODO")
        }

        // to test getReviews
        should("test getReviews") {
            // uncomment below to test getReviews
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : GetReviews200Response = apiInstance.getReviews(productId, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test getSearchHistory
        should("test getSearchHistory") {
            // uncomment below to test getSearchHistory
            //val result : SearchHistoryEnvelope = apiInstance.getSearchHistory()
            //result shouldBe ("TODO")
        }

        // to test listCategories
        should("test listCategories") {
            // uncomment below to test listCategories
            //val result : ListCategories200Response = apiInstance.listCategories()
            //result shouldBe ("TODO")
        }

        // to test searchProducts
        should("test searchProducts") {
            // uncomment below to test searchProducts
            //val q : kotlin.String = q_example // kotlin.String | 
            //val minPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val maxPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val minRating : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val freeShipping : kotlin.Boolean = true // kotlin.Boolean | 
            //val express : kotlin.Boolean = true // kotlin.Boolean | 
            //val brand : kotlin.String = brand_example // kotlin.String | 
            //val sortBy : SortOption =  // SortOption | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : SearchProducts200Response = apiInstance.searchProducts(q, minPrice, maxPrice, minRating, freeShipping, express, brand, sortBy, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test searchSuggestions
        should("test searchSuggestions") {
            // uncomment below to test searchSuggestions
            //val q : kotlin.String = q_example // kotlin.String | 
            //val result : SearchSuggestions200Response = apiInstance.searchSuggestions(q)
            //result shouldBe ("TODO")
        }

    }
}
