/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.CheckoutApi
import com.citybox.api.models.CheckoutPreview200Response
import com.citybox.api.models.CheckoutPreviewRequest
import com.citybox.api.models.CheckoutSessionEnvelope
import com.citybox.api.models.CreateOrder201Response
import com.citybox.api.models.CreateOrderRequest
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetShippingOptions200Response
import com.citybox.api.models.GetShippingOptionsRequest
import com.citybox.api.models.ListCoupons200Response
import com.citybox.api.models.RemoveCoupon200Response
import com.citybox.api.models.UpdateCheckoutSessionRequest
import com.citybox.api.models.ValidateCoupon200Response
import com.citybox.api.models.ValidateCouponRequest

class CheckoutApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutApi
        //val apiInstance = CheckoutApi()

        // to test checkoutPreview
        should("test checkoutPreview") {
            // uncomment below to test checkoutPreview
            //val checkoutPreviewRequest : CheckoutPreviewRequest =  // CheckoutPreviewRequest | 
            //val result : CheckoutPreview200Response = apiInstance.checkoutPreview(checkoutPreviewRequest)
            //result shouldBe ("TODO")
        }

        // to test createOrder
        should("test createOrder") {
            // uncomment below to test createOrder
            //val idempotencyKey : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | UUID v4 para evitar pedido duplicado em retry
            //val createOrderRequest : CreateOrderRequest =  // CreateOrderRequest | 
            //val result : CreateOrder201Response = apiInstance.createOrder(idempotencyKey, createOrderRequest)
            //result shouldBe ("TODO")
        }

        // to test getCheckoutSession
        should("test getCheckoutSession") {
            // uncomment below to test getCheckoutSession
            //val result : CheckoutSessionEnvelope = apiInstance.getCheckoutSession()
            //result shouldBe ("TODO")
        }

        // to test getShippingOptions
        should("test getShippingOptions") {
            // uncomment below to test getShippingOptions
            //val getShippingOptionsRequest : GetShippingOptionsRequest =  // GetShippingOptionsRequest | 
            //val result : GetShippingOptions200Response = apiInstance.getShippingOptions(getShippingOptionsRequest)
            //result shouldBe ("TODO")
        }

        // to test listCoupons
        should("test listCoupons") {
            // uncomment below to test listCoupons
            //val result : ListCoupons200Response = apiInstance.listCoupons()
            //result shouldBe ("TODO")
        }

        // to test removeCoupon
        should("test removeCoupon") {
            // uncomment below to test removeCoupon
            //val result : RemoveCoupon200Response = apiInstance.removeCoupon()
            //result shouldBe ("TODO")
        }

        // to test updateCheckoutSession
        should("test updateCheckoutSession") {
            // uncomment below to test updateCheckoutSession
            //val updateCheckoutSessionRequest : UpdateCheckoutSessionRequest =  // UpdateCheckoutSessionRequest | 
            //val result : CheckoutSessionEnvelope = apiInstance.updateCheckoutSession(updateCheckoutSessionRequest)
            //result shouldBe ("TODO")
        }

        // to test validateCoupon
        should("test validateCoupon") {
            // uncomment below to test validateCoupon
            //val validateCouponRequest : ValidateCouponRequest =  // ValidateCouponRequest | 
            //val result : ValidateCoupon200Response = apiInstance.validateCoupon(validateCouponRequest)
            //result shouldBe ("TODO")
        }

    }
}
