/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.ContedoApi
import com.citybox.api.models.GetBanners200Response
import com.citybox.api.models.GetStaticPage200Response

class ContedoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ContedoApi
        //val apiInstance = ContedoApi()

        // to test getBanners
        should("test getBanners") {
            // uncomment below to test getBanners
            //val result : GetBanners200Response = apiInstance.getBanners()
            //result shouldBe ("TODO")
        }

        // to test getStaticPage
        should("test getStaticPage") {
            // uncomment below to test getStaticPage
            //val slug : kotlin.String = slug_example // kotlin.String | 
            //val result : GetStaticPage200Response = apiInstance.getStaticPage(slug)
            //result shouldBe ("TODO")
        }

    }
}
