/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.ConteudoApi
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetBanners200Response
import com.citybox.api.models.GetStaticPage200Response
import com.citybox.api.models.HealthResponse
import com.citybox.api.models.MockRootResponse

class ConteudoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConteudoApi
        //val apiInstance = ConteudoApi()

        // to test getBanners
        should("test getBanners") {
            // uncomment below to test getBanners
            //val result : GetBanners200Response = apiInstance.getBanners()
            //result shouldBe ("TODO")
        }

        // to test getHealth
        should("test getHealth") {
            // uncomment below to test getHealth
            //val result : HealthResponse = apiInstance.getHealth()
            //result shouldBe ("TODO")
        }

        // to test getRoot
        should("test getRoot") {
            // uncomment below to test getRoot
            //val result : MockRootResponse = apiInstance.getRoot()
            //result shouldBe ("TODO")
        }

        // to test getStaticPage
        should("test getStaticPage") {
            // uncomment below to test getStaticPage
            //val slug : kotlin.String = slug_example // kotlin.String | 
            //val result : GetStaticPage200Response = apiInstance.getStaticPage(slug)
            //result shouldBe ("TODO")
        }

    }
}
