/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.EnderecosApi
import com.citybox.api.models.AddressEnvelope
import com.citybox.api.models.AddressInput
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.ListAddresses200Response
import com.citybox.api.models.LookupZip200Response

class EnderecosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnderecosApi
        //val apiInstance = EnderecosApi()

        // to test createAddress
        should("test createAddress") {
            // uncomment below to test createAddress
            //val addressInput : AddressInput =  // AddressInput | 
            //val result : AddressEnvelope = apiInstance.createAddress(addressInput)
            //result shouldBe ("TODO")
        }

        // to test deleteAddress
        should("test deleteAddress") {
            // uncomment below to test deleteAddress
            //val addressId : kotlin.String = addr-1 // kotlin.String | 
            //apiInstance.deleteAddress(addressId)
        }

        // to test listAddresses
        should("test listAddresses") {
            // uncomment below to test listAddresses
            //val result : ListAddresses200Response = apiInstance.listAddresses()
            //result shouldBe ("TODO")
        }

        // to test lookupZip
        should("test lookupZip") {
            // uncomment below to test lookupZip
            //val zipCode : kotlin.String = 01310-100 // kotlin.String | 
            //val result : LookupZip200Response = apiInstance.lookupZip(zipCode)
            //result shouldBe ("TODO")
        }

        // to test setDefaultAddress
        should("test setDefaultAddress") {
            // uncomment below to test setDefaultAddress
            //val addressId : kotlin.String = addr-1 // kotlin.String | 
            //val result : AddressEnvelope = apiInstance.setDefaultAddress(addressId)
            //result shouldBe ("TODO")
        }

        // to test updateAddress
        should("test updateAddress") {
            // uncomment below to test updateAddress
            //val addressId : kotlin.String = addr-1 // kotlin.String | 
            //val addressInput : AddressInput =  // AddressInput | 
            //val result : AddressEnvelope = apiInstance.updateAddress(addressId, addressInput)
            //result shouldBe ("TODO")
        }

    }
}
