/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.EngajamentoApi
import com.citybox.api.models.CreateTicket201Response
import com.citybox.api.models.CreateTicketRequest
import com.citybox.api.models.GetChatMessages200Response
import com.citybox.api.models.GetFaq200Response
import com.citybox.api.models.ListNotifications200Response
import com.citybox.api.models.MarkAllNotificationsRead200Response
import com.citybox.api.models.MarkNotificationRead200Response
import com.citybox.api.models.SendChatMessage201Response
import com.citybox.api.models.SendChatMessageRequest

class EngajamentoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EngajamentoApi
        //val apiInstance = EngajamentoApi()

        // to test createTicket
        should("test createTicket") {
            // uncomment below to test createTicket
            //val createTicketRequest : CreateTicketRequest =  // CreateTicketRequest | 
            //val result : CreateTicket201Response = apiInstance.createTicket(createTicketRequest)
            //result shouldBe ("TODO")
        }

        // to test getChatMessages
        should("test getChatMessages") {
            // uncomment below to test getChatMessages
            //val before : kotlin.String = before_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : GetChatMessages200Response = apiInstance.getChatMessages(before, limit)
            //result shouldBe ("TODO")
        }

        // to test getFaq
        should("test getFaq") {
            // uncomment below to test getFaq
            //val result : GetFaq200Response = apiInstance.getFaq()
            //result shouldBe ("TODO")
        }

        // to test listNotifications
        should("test listNotifications") {
            // uncomment below to test listNotifications
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val unreadOnly : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : ListNotifications200Response = apiInstance.listNotifications(page, pageSize, unreadOnly)
            //result shouldBe ("TODO")
        }

        // to test markAllNotificationsRead
        should("test markAllNotificationsRead") {
            // uncomment below to test markAllNotificationsRead
            //val result : MarkAllNotificationsRead200Response = apiInstance.markAllNotificationsRead()
            //result shouldBe ("TODO")
        }

        // to test markNotificationRead
        should("test markNotificationRead") {
            // uncomment below to test markNotificationRead
            //val notificationId : kotlin.String = notificationId_example // kotlin.String | 
            //val result : MarkNotificationRead200Response = apiInstance.markNotificationRead(notificationId)
            //result shouldBe ("TODO")
        }

        // to test sendChatMessage
        should("test sendChatMessage") {
            // uncomment below to test sendChatMessage
            //val sendChatMessageRequest : SendChatMessageRequest =  // SendChatMessageRequest | 
            //val result : SendChatMessage201Response = apiInstance.sendChatMessage(sendChatMessageRequest)
            //result shouldBe ("TODO")
        }

    }
}
