/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.FavoritosApi
import com.citybox.api.models.ListFavorites200Response
import com.citybox.api.models.ToggleFavorite200Response
import com.citybox.api.models.ToggleFavoriteRequest

class FavoritosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FavoritosApi
        //val apiInstance = FavoritosApi()

        // to test listFavorites
        should("test listFavorites") {
            // uncomment below to test listFavorites
            //val result : ListFavorites200Response = apiInstance.listFavorites()
            //result shouldBe ("TODO")
        }

        // to test toggleFavorite
        should("test toggleFavorite") {
            // uncomment below to test toggleFavorite
            //val productId : kotlin.String = iphone15pro // kotlin.String | 
            //val toggleFavoriteRequest : ToggleFavoriteRequest =  // ToggleFavoriteRequest | 
            //val result : ToggleFavorite200Response = apiInstance.toggleFavorite(productId, toggleFavoriteRequest)
            //result shouldBe ("TODO")
        }

    }
}
