/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.PagamentosApi
import com.citybox.api.models.CreatePaymentMethod201Response
import com.citybox.api.models.CreatePaymentMethodRequest
import com.citybox.api.models.ListPaymentMethods200Response
import com.citybox.api.models.SetDefaultPaymentMethod200Response

class PagamentosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PagamentosApi
        //val apiInstance = PagamentosApi()

        // to test createPaymentMethod
        should("test createPaymentMethod") {
            // uncomment below to test createPaymentMethod
            //val createPaymentMethodRequest : CreatePaymentMethodRequest =  // CreatePaymentMethodRequest | 
            //val result : CreatePaymentMethod201Response = apiInstance.createPaymentMethod(createPaymentMethodRequest)
            //result shouldBe ("TODO")
        }

        // to test deletePaymentMethod
        should("test deletePaymentMethod") {
            // uncomment below to test deletePaymentMethod
            //val paymentMethodId : kotlin.String = card-1 // kotlin.String | 
            //apiInstance.deletePaymentMethod(paymentMethodId)
        }

        // to test listPaymentMethods
        should("test listPaymentMethods") {
            // uncomment below to test listPaymentMethods
            //val result : ListPaymentMethods200Response = apiInstance.listPaymentMethods()
            //result shouldBe ("TODO")
        }

        // to test setDefaultPaymentMethod
        should("test setDefaultPaymentMethod") {
            // uncomment below to test setDefaultPaymentMethod
            //val paymentMethodId : kotlin.String = card-1 // kotlin.String | 
            //val result : SetDefaultPaymentMethod200Response = apiInstance.setDefaultPaymentMethod(paymentMethodId)
            //result shouldBe ("TODO")
        }

    }
}
