/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.PedidosApi
import com.citybox.api.models.BuyAgain200Response
import com.citybox.api.models.CancelOrderRequest
import com.citybox.api.models.CreateReturn201Response
import com.citybox.api.models.CreateReturnRequest
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetInvoice200Response
import com.citybox.api.models.GetOrder200Response
import com.citybox.api.models.GetReturn200Response
import com.citybox.api.models.GetTracking200Response
import com.citybox.api.models.ListOrders200Response
import com.citybox.api.models.OrderStatus

class PedidosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PedidosApi
        //val apiInstance = PedidosApi()

        // to test buyAgain
        should("test buyAgain") {
            // uncomment below to test buyAgain
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val result : BuyAgain200Response = apiInstance.buyAgain(orderId)
            //result shouldBe ("TODO")
        }

        // to test cancelOrder
        should("test cancelOrder") {
            // uncomment below to test cancelOrder
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val cancelOrderRequest : CancelOrderRequest =  // CancelOrderRequest | 
            //val result : GetOrder200Response = apiInstance.cancelOrder(orderId, cancelOrderRequest)
            //result shouldBe ("TODO")
        }

        // to test createReturn
        should("test createReturn") {
            // uncomment below to test createReturn
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val createReturnRequest : CreateReturnRequest =  // CreateReturnRequest | 
            //val result : CreateReturn201Response = apiInstance.createReturn(orderId, createReturnRequest)
            //result shouldBe ("TODO")
        }

        // to test getInvoice
        should("test getInvoice") {
            // uncomment below to test getInvoice
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val result : GetInvoice200Response = apiInstance.getInvoice(orderId)
            //result shouldBe ("TODO")
        }

        // to test getOrder
        should("test getOrder") {
            // uncomment below to test getOrder
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val ifNoneMatch : kotlin.String = ifNoneMatch_example // kotlin.String | 
            //val result : GetOrder200Response = apiInstance.getOrder(orderId, ifNoneMatch)
            //result shouldBe ("TODO")
        }

        // to test getReturn
        should("test getReturn") {
            // uncomment below to test getReturn
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val returnId : kotlin.String = returnId_example // kotlin.String | 
            //val result : GetReturn200Response = apiInstance.getReturn(orderId, returnId)
            //result shouldBe ("TODO")
        }

        // to test getTracking
        should("test getTracking") {
            // uncomment below to test getTracking
            //val orderId : kotlin.String = CB-001234 // kotlin.String | 
            //val result : GetTracking200Response = apiInstance.getTracking(orderId)
            //result shouldBe ("TODO")
        }

        // to test listOrders
        should("test listOrders") {
            // uncomment below to test listOrders
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val status : OrderStatus =  // OrderStatus | 
            //val result : ListOrders200Response = apiInstance.listOrders(page, pageSize, status)
            //result shouldBe ("TODO")
        }

    }
}
