/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.citybox.api.apis.PerfilContaApi
import com.citybox.api.models.DeleteAccountRequest
import com.citybox.api.models.ErrorEnvelope
import com.citybox.api.models.GetMe200Response
import com.citybox.api.models.GetSettings200Response
import com.citybox.api.models.Settings
import com.citybox.api.models.UpdateMeRequest
import com.citybox.api.models.UploadAvatar200Response

class PerfilContaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerfilContaApi
        //val apiInstance = PerfilContaApi()

        // to test deleteAccount
        should("test deleteAccount") {
            // uncomment below to test deleteAccount
            //val deleteAccountRequest : DeleteAccountRequest =  // DeleteAccountRequest | 
            //apiInstance.deleteAccount(deleteAccountRequest)
        }

        // to test getMe
        should("test getMe") {
            // uncomment below to test getMe
            //val result : GetMe200Response = apiInstance.getMe()
            //result shouldBe ("TODO")
        }

        // to test getSettings
        should("test getSettings") {
            // uncomment below to test getSettings
            //val result : GetSettings200Response = apiInstance.getSettings()
            //result shouldBe ("TODO")
        }

        // to test updateMe
        should("test updateMe") {
            // uncomment below to test updateMe
            //val updateMeRequest : UpdateMeRequest =  // UpdateMeRequest | 
            //val result : GetMe200Response = apiInstance.updateMe(updateMeRequest)
            //result shouldBe ("TODO")
        }

        // to test updateSettings
        should("test updateSettings") {
            // uncomment below to test updateSettings
            //val settings : Settings =  // Settings | 
            //val result : GetSettings200Response = apiInstance.updateSettings(settings)
            //result shouldBe ("TODO")
        }

        // to test uploadAvatar
        should("test uploadAvatar") {
            // uncomment below to test uploadAvatar
            //val file : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : UploadAvatar200Response = apiInstance.uploadAvatar(file)
            //result shouldBe ("TODO")
        }

    }
}
