/** Seed: biblioteca + templates de anamnese. */
export type ClinicSeedAnamnesisQuestion = {
  text: string;
  type:
    | 'text'
    | 'yes_no_unknown'
    | 'yes_no_unknown_text'
    | 'left_right_unknown'
    | 'rich_text'
    | 'single_choice';
  generatesAlert: boolean;
  alertWhen: 'yes' | 'no' | null;
  alertName: string | null;
  options?: Array<{
    value: string;
    label: string;
    allowsOther?: boolean;
  }>;
};

export type ClinicSeedAnamnesisTemplate = {
  name: string;
  activeQuestionTexts: string[];
};

export const ANAMNESIS_QUESTION_LIBRARY: ClinicSeedAnamnesisQuestion[] = [
  {
    text: "Sente alguma dor nos dentes ou na boca?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Está em tratamento médico?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Está usando medicação?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Toma",
  },
  {
    text: "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Alérgico a",
  },
  {
    text: "Já esteve internado?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já teve hemorragia diagnosticada?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Risco de hemorragia",
  },
  {
    text: "Possui alguma alteração sanguínea?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Alteração sanguínea",
  },
  {
    text: "Tem pressão alta?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Hipertenso",
  },
  {
    text: "Possui diabetes?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Diabético",
  },
  {
    text: "Possui asma?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Asmático",
  },
  {
    text: "Possui anemia?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Anêmico",
  },
  {
    text: "Possui alguma disfunção hepática?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Disfunção hepática",
  },
  {
    text: "Apresenta alguma disfunção renal?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Problema renal",
  },
  {
    text: "Possui alguma disfunção respiratória?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Problema respiratório",
  },
  {
    text: "Possui alguma alteração óssea?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Alteração óssea",
  },
  {
    text: "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Doença transmissível",
  },
  {
    text: "Possui câncer?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Câncer",
  },
  {
    text: "Possui depressão?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Está ou esteve em tratamento psicológico?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui algum antecedente de febre reumática?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui algum antecedente de endocardite bacteriana?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Antecedente de endocardite bacteriana",
  },
  {
    text: "Possui alguma outra doença/síndrome não mencionada?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Outra doença/síndrome",
  },
  {
    text: "Já sofreu alguma reação alérgica ao receber anestesia?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Alérgico ao anestésico",
  },
  {
    text: "Escuta algum estalido ao abrir a boca?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Tem dificuldade de abrir a boca?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Sente dores no ouvido, cabeça, face, nuca ou pescoço?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui mau hálito?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui azia, má digestão, refluxo, úlcera ou gastrite?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta sangramento a escovação?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Sente seus dentes moles?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Seus dentes são sensíveis a mudança de temperatura ou a alimentos doces?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Range os dentes?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Ortodontia (aparelhos e correção)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Periodontia (tratamento gengival)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Endodontia (tratamento de canal)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Profilaxia / Prevenção (limpeza, flúor, selante oclusal, etc.)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Quantas vezes por dia escova os dentes?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Usa creme dental?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Usa fio dental?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Faz uso de antisséptico bucal?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Come muitos doces, balas entre outros?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Tem hábito de tomar café ou refrigerantes?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Ingere bebidas alcoólicas?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Fumante?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Usa drogas?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Tem o hábito de roer unha ou morder objetos (lápis, caneta, etc.)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Está grávida?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Grávida",
  },
  {
    text: "Está amamentando?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Toma anticoncepcional?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual a pressão arterial do paciente?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual frequência respiratória por minuto do paciente?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual a frequência cardíaca por minuto(bpm) do paciente?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "O paciente possui alguma alteração ganglionar?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta alguma alteração de língua, lábio e/ou palato?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta outra alteração na face não mencionada?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Informações adicionais:",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você está com febre ou teve febre nos últimos 14 dias?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você teve alguma experiência de início de problemas respiratórios, como tosse ou dificuldade de respirar nos últimos 14 dias?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você teve algum tipo de contato com alguma pessoa confirmadamente infectada pelo 2019-nCoV nos últimos 14 dias?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você teve contato com um grande número de pessoas diferentes no últimos 14 dias?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você está usando máscara, álcool em gel ou outras medidas de biossegurança no seu dia a dia?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu à Cirurgia?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Realizou cirurgia bariátrica?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui alguma alteração cardiovascular?",
    type: "yes_no_unknown_text",
    generatesAlert: true,
    alertWhen: "yes",
    alertName: "Alteração cardíaca",
  },
  {
    text: "Tem muita exposição solar?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta manchas na pele?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta flacidez na pele?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Apresenta lesões de acne ativas?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já realizou algum tratamento estético facial ou de pele?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Já se submeteu a tratamentos com preenchedores não reabsorvíveis (PMMA)?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Fez uso de ácido ou algum peeling químico?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Usa filtro solar regularmente?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Faz uso de produtos de cuidado diário da pele?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "O que você sente quando se olha no espelho?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "O que você gostaria de melhorar no seu rosto?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Você prefere resultados mais rápidos e mais caros ou mais lentos e mais baratos?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Realizou pré natal?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "A criança nasceu com parto normal ou cesariana?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Peso ao nascer?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Realiza(ou) aleitamento materno?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Realiza(ou) o uso de mamadeira ou chupeta?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Realiza(ou) sucção de dedo ou lábio?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual o perfil? (côncavo, convexo ou reto)",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual a sobremordida? (aumentada, normal ou aberta)",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual o trespasse horizontal? (aumentado, normal ou negativo)",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui mordida cruzada?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Possui desvio de linha média?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "O canino direito apresenta relação de: classe I, classe II, classe III ou topo?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "O canino esquerdo apresenta relação de: classe I, classe II, classe III ou topo?",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Qual a classe do paciente? (Classe I, II ou III)",
    type: "yes_no_unknown_text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
  {
    text: "Queixa principal?",
    type: "text",
    generatesAlert: false,
    alertWhen: null,
    alertName: null,
  },
];

export const ANAMNESIS_TEMPLATES: ClinicSeedAnamnesisTemplate[] = [
  {
    name: "Anamnese adulta",
    activeQuestionTexts: [
      "Sente alguma dor nos dentes ou na boca?",
      "Está em tratamento médico?",
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já esteve internado?",
      "Já teve hemorragia diagnosticada?",
      "Possui alguma alteração sanguínea?",
      "Tem pressão alta?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui anemia?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma disfunção respiratória?",
      "Possui alguma alteração óssea?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui câncer?",
      "Possui depressão?",
      "Está ou esteve em tratamento psicológico?",
      "Possui algum antecedente de febre reumática?",
      "Possui algum antecedente de endocardite bacteriana?",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já sofreu alguma reação alérgica ao receber anestesia?",
      "Escuta algum estalido ao abrir a boca?",
      "Tem dificuldade de abrir a boca?",
      "Sente dores no ouvido, cabeça, face, nuca ou pescoço?",
      "Possui mau hálito?",
      "Possui azia, má digestão, refluxo, úlcera ou gastrite?",
      "Apresenta sangramento a escovação?",
      "Sente seus dentes moles?",
      "Seus dentes são sensíveis a mudança de temperatura ou a alimentos doces?",
      "Range os dentes?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Já se submeteu à Ortodontia (aparelhos e correção)?",
      "Já se submeteu à Periodontia (tratamento gengival)?",
      "Já se submeteu à Endodontia (tratamento de canal)?",
      "Já se submeteu à Profilaxia / Prevenção (limpeza, flúor, selante oclusal, etc.)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa creme dental?",
      "Usa fio dental?",
      "Faz uso de antisséptico bucal?",
      "Come muitos doces, balas entre outros?",
      "Tem hábito de tomar café ou refrigerantes?",
      "Ingere bebidas alcoólicas?",
      "Fumante?",
      "Usa drogas?",
      "Tem o hábito de roer unha ou morder objetos (lápis, caneta, etc.)?",
      "Está grávida?",
      "Está amamentando?",
      "Toma anticoncepcional?",
      "Qual a pressão arterial do paciente?",
      "Qual frequência respiratória por minuto do paciente?",
      "Qual a frequência cardíaca por minuto(bpm) do paciente?",
      "O paciente possui alguma alteração ganglionar?",
      "Apresenta alguma alteração de língua, lábio e/ou palato?",
      "Apresenta outra alteração na face não mencionada?",
      "Informações adicionais:",
      "Você está com febre ou teve febre nos últimos 14 dias?",
      "Você teve alguma experiência de início de problemas respiratórios, como tosse ou dificuldade de respirar nos últimos 14 dias?",
      "Você teve algum tipo de contato com alguma pessoa confirmadamente infectada pelo 2019-nCoV nos últimos 14 dias?",
      "Você teve contato com um grande número de pessoas diferentes no últimos 14 dias?",
      "Você está usando máscara, álcool em gel ou outras medidas de biossegurança no seu dia a dia?",
    ],
  },
  {
    name: "Anamnese adulta resumida",
    activeQuestionTexts: [
      "Queixa principal?",
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já teve hemorragia diagnosticada?",
      "Tem pressão alta?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa fio dental?",
      "Come muitos doces, balas entre outros?",
      "Você está com febre ou teve febre nos últimos 14 dias?",
      "Está grávida?",
      "Está amamentando?",
      "Informações adicionais:",
    ],
  },
  {
    name: "Anamnese HOF",
    activeQuestionTexts: [
      "Está em tratamento médico?",
      "Está usando medicação?",
      "Toma anticoncepcional?",
      "Tem pressão alta?",
      "Possui asma?",
      "Possui diabetes?",
      "Possui anemia?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Possui câncer?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Já se submeteu à Cirurgia?",
      "Realizou cirurgia bariátrica?",
      "Já sofreu alguma reação alérgica ao receber anestesia?",
      "Possui alguma alteração cardiovascular?",
      "Possui alguma alteração sanguínea?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma disfunção respiratória?",
      "Já teve hemorragia diagnosticada?",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Apresenta outra alteração na face não mencionada?",
      "Tem dificuldade de abrir a boca?",
      "Sente alguma dor nos dentes ou na boca?",
      "Está amamentando?",
      "Está grávida?",
      "Está ou esteve em tratamento psicológico?",
      "Ingere bebidas alcoólicas?",
      "Fumante?",
      "Tem muita exposição solar?",
      "Apresenta manchas na pele?",
      "Apresenta flacidez na pele?",
      "Apresenta lesões de acne ativas?",
      "Já realizou algum tratamento estético facial ou de pele?",
      "Já se submeteu a tratamentos com preenchedores não reabsorvíveis (PMMA)?",
      "Fez uso de ácido ou algum peeling químico?",
      "Usa filtro solar regularmente?",
      "Faz uso de produtos de cuidado diário da pele?",
      "O que você sente quando se olha no espelho?",
      "O que você gostaria de melhorar no seu rosto?",
      "Você prefere resultados mais rápidos e mais caros ou mais lentos e mais baratos?",
      "Informações adicionais:",
    ],
  },
  {
    name: "Anamnese infantil",
    activeQuestionTexts: [
      "Sente alguma dor nos dentes ou na boca?",
      "Está em tratamento médico?",
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já esteve internado?",
      "Já teve hemorragia diagnosticada?",
      "Possui alguma alteração sanguínea?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui anemia?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma disfunção respiratória?",
      "Possui alguma alteração óssea?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui câncer?",
      "Possui depressão?",
      "Está ou esteve em tratamento psicológico?",
      "Possui algum antecedente de febre reumática?",
      "Possui algum antecedente de endocardite bacteriana?",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já sofreu alguma reação alérgica ao receber anestesia?",
      "Tem dificuldade de abrir a boca?",
      "Sente dores no ouvido, cabeça, face, nuca ou pescoço?",
      "Possui mau hálito?",
      "Possui azia, má digestão, refluxo, úlcera ou gastrite?",
      "Apresenta sangramento a escovação?",
      "Seus dentes são sensíveis a mudança de temperatura ou a alimentos doces?",
      "Range os dentes?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Já se submeteu à Ortodontia (aparelhos e correção)?",
      "Já se submeteu à Periodontia (tratamento gengival)?",
      "Já se submeteu à Endodontia (tratamento de canal)?",
      "Já se submeteu à Profilaxia / Prevenção (limpeza, flúor, selante oclusal, etc.)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa creme dental?",
      "Usa fio dental?",
      "Faz uso de antisséptico bucal?",
      "Come muitos doces, balas entre outros?",
      "Tem hábito de tomar café ou refrigerantes?",
      "Tem o hábito de roer unha ou morder objetos (lápis, caneta, etc.)?",
      "Realizou pré natal?",
      "A criança nasceu com parto normal ou cesariana?",
      "Peso ao nascer?",
      "Realiza(ou) aleitamento materno?",
      "Realiza(ou) o uso de mamadeira ou chupeta?",
      "Realiza(ou) sucção de dedo ou lábio?",
      "Qual a pressão arterial do paciente?",
      "Qual frequência respiratória por minuto do paciente?",
      "Qual a frequência cardíaca por minuto(bpm) do paciente?",
      "O paciente possui alguma alteração ganglionar?",
      "Apresenta alguma alteração de língua, lábio e/ou palato?",
      "Apresenta outra alteração na face não mencionada?",
      "Informações adicionais:",
    ],
  },
  {
    name: "Anamnese infantil resumida",
    activeQuestionTexts: [
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já teve hemorragia diagnosticada?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa fio dental?",
      "Come muitos doces, balas entre outros?",
      "Realizou pré natal?",
      "A criança nasceu com parto normal ou cesariana?",
      "Peso ao nascer?",
      "Realiza(ou) aleitamento materno?",
      "Realiza(ou) o uso de mamadeira ou chupeta?",
      "Realiza(ou) sucção de dedo ou lábio?",
      "Informações adicionais:",
    ],
  },
  {
    name: "Anamnese ortodôntica",
    activeQuestionTexts: [
      "Sente alguma dor nos dentes ou na boca?",
      "Está em tratamento médico?",
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já esteve internado?",
      "Já teve hemorragia diagnosticada?",
      "Possui alguma alteração sanguínea?",
      "Tem pressão alta?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui anemia?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma disfunção respiratória?",
      "Possui alguma alteração óssea?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui câncer?",
      "Possui depressão?",
      "Está ou esteve em tratamento psicológico?",
      "Possui algum antecedente de febre reumática?",
      "Possui algum antecedente de endocardite bacteriana?",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já sofreu alguma reação alérgica ao receber anestesia?",
      "Tem dificuldade de abrir a boca?",
      "Sente dores no ouvido, cabeça, face, nuca ou pescoço?",
      "Possui mau hálito?",
      "Possui azia, má digestão, refluxo, úlcera ou gastrite?",
      "Apresenta sangramento a escovação?",
      "Seus dentes são sensíveis a mudança de temperatura ou a alimentos doces?",
      "Range os dentes?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Já se submeteu à Ortodontia (aparelhos e correção)?",
      "Já se submeteu à Periodontia (tratamento gengival)?",
      "Já se submeteu à Endodontia (tratamento de canal)?",
      "Já se submeteu à Profilaxia / Prevenção (limpeza, flúor, selante oclusal, etc.)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa creme dental?",
      "Usa fio dental?",
      "Faz uso de antisséptico bucal?",
      "Come muitos doces, balas entre outros?",
      "Tem hábito de tomar café ou refrigerantes?",
      "Tem o hábito de roer unha ou morder objetos (lápis, caneta, etc.)?",
      "Realizou pré natal?",
      "A criança nasceu com parto normal ou cesariana?",
      "Peso ao nascer?",
      "Realiza(ou) aleitamento materno?",
      "Realiza(ou) o uso de mamadeira ou chupeta?",
      "Realiza(ou) sucção de dedo ou lábio?",
      "Qual o perfil? (côncavo, convexo ou reto)",
      "Qual a sobremordida? (aumentada, normal ou aberta)",
      "Qual o trespasse horizontal? (aumentado, normal ou negativo)",
      "Possui mordida cruzada?",
      "Possui desvio de linha média?",
      "O canino direito apresenta relação de: classe I, classe II, classe III ou topo?",
      "O canino esquerdo apresenta relação de: classe I, classe II, classe III ou topo?",
      "Qual a classe do paciente? (Classe I, II ou III)",
      "Qual a pressão arterial do paciente?",
      "Qual frequência respiratória por minuto do paciente?",
      "Qual a frequência cardíaca por minuto(bpm) do paciente?",
      "O paciente possui alguma alteração ganglionar?",
      "Apresenta alguma alteração de língua, lábio e/ou palato?",
      "Apresenta outra alteração na face não mencionada?",
      "Informações adicionais:",
    ],
  },
  {
    name: "Anamnese ortodôntica resumida",
    activeQuestionTexts: [
      "Está usando medicação?",
      "Possui alguma alergia? (Como penicilinas, AAS ou outra)",
      "Já teve hemorragia diagnosticada?",
      "Tem pressão alta?",
      "Possui diabetes?",
      "Possui asma?",
      "Possui alguma disfunção hepática?",
      "Apresenta alguma disfunção renal?",
      "Possui alguma doença transmissível? (HIV, Hepatite, outra)",
      "Possui alguma outra doença/síndrome não mencionada?",
      "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?",
      "Já se submeteu à Ortodontia (aparelhos e correção)?",
      "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?",
      "Quantas vezes por dia escova os dentes?",
      "Usa fio dental?",
      "Come muitos doces, balas entre outros?",
      "Realiza(ou) o uso de mamadeira ou chupeta?",
      "Realiza(ou) sucção de dedo ou lábio?",
      "Qual o perfil? (côncavo, convexo ou reto)",
      "Qual a sobremordida? (aumentada, normal ou aberta)",
      "Qual o trespasse horizontal? (aumentado, normal ou negativo)",
      "Possui mordida cruzada?",
      "Possui desvio de linha média?",
      "O canino direito apresenta relação de: classe I, classe II, classe III ou topo?",
      "O canino esquerdo apresenta relação de: classe I, classe II, classe III ou topo?",
      "Qual a classe do paciente? (Classe I, II ou III)",
      "Informações adicionais:",
    ],
  },
];

