/** Seed data: plano Particular — especialidades e tratamentos. */
export type ClinicSeedTreatment = {
  name: string;
  acceptsFaces: boolean;
  valueCents: number;
  costCents: number;
};

export type ClinicSeedSpecialty = {
  name: string;
  treatments: ClinicSeedTreatment[];
};

export const PARTICULAR_SPECIALTIES: ClinicSeedSpecialty[] = [
  {
    name: "Cirurgia",
    treatments: [
      { name: "Alveoloplastia", acceptsFaces: false, valueCents: 25258, costCents: 0 },
      { name: "Amputação Radicular com Obturação Retrógrada", acceptsFaces: false, valueCents: 29086, costCents: 0 },
      { name: "Amputação Radicular sem Obturação Retrógrada", acceptsFaces: false, valueCents: 30598, costCents: 0 },
      { name: "Apicetomia Birradiculares com Obturação Retrógrada", acceptsFaces: false, valueCents: 34411, costCents: 10323 },
      { name: "Apicetomia Birradiculares sem Obturação Retrógrada", acceptsFaces: false, valueCents: 40918, costCents: 0 },
      { name: "Apicetomia Multirradiculares com Obturação Retrógrada", acceptsFaces: false, valueCents: 10015, costCents: 3004 },
      { name: "Apicetomia Multirradiculares sem Obturação Retrógrada", acceptsFaces: false, valueCents: 12951, costCents: 3885 },
      { name: "Apicetomia Unirradiculares com Obturação Retrógrada", acceptsFaces: false, valueCents: 45180, costCents: 0 },
      { name: "Apicetomia Unirradiculares sem Obturação Retrógrada", acceptsFaces: false, valueCents: 11474, costCents: 0 },
      { name: "Aumento de Vestíbulo (Sulcoplastia)", acceptsFaces: false, valueCents: 34622, costCents: 0 },
      { name: "Biópsia de Boca", acceptsFaces: false, valueCents: 45978, costCents: 0 },
      { name: "Biópsia de Glândula Salivar", acceptsFaces: false, valueCents: 16032, costCents: 0 },
      { name: "Biópsia de Lábio", acceptsFaces: false, valueCents: 46979, costCents: 14093 },
      { name: "Biópsia de Língua", acceptsFaces: false, valueCents: 18738, costCents: 0 },
      { name: "Biópsia de Mandíbula", acceptsFaces: false, valueCents: 33070, costCents: 0 },
      { name: "Biópsia de Maxila", acceptsFaces: false, valueCents: 9253, costCents: 2775 },
      { name: "Bridectomia", acceptsFaces: false, valueCents: 44492, costCents: 0 },
      { name: "Bridotomia", acceptsFaces: false, valueCents: 45387, costCents: 13616 },
      { name: "Cirurgia com Retalho", acceptsFaces: false, valueCents: 42494, costCents: 0 },
      { name: "Cirurgia para Torus Mandibular Bilateral", acceptsFaces: false, valueCents: 40683, costCents: 12204 },
      { name: "Cirurgia para Torus Mandibular Unilateral", acceptsFaces: false, valueCents: 18077, costCents: 5423 },
      { name: "Cirurgia para Torus Palatinio", acceptsFaces: false, valueCents: 41529, costCents: 12458 },
      { name: "Coleta por Raspagem em Lesões", acceptsFaces: false, valueCents: 23615, costCents: 7084 },
      { name: "Controle Pós-operatório em Odontologia", acceptsFaces: false, valueCents: 20167, costCents: 6050 },
      { name: "Enxerto Conjuntivo Subepitelial", acceptsFaces: false, valueCents: 10601, costCents: 3180 },
      { name: "Exérese ou Excisão de Cálculo Salivar", acceptsFaces: false, valueCents: 33767, costCents: 10130 },
      { name: "Exérese ou Excisão de Cistos Odontológicos", acceptsFaces: false, valueCents: 45564, costCents: 0 },
      { name: "Exérese ou Excisão de Mucocele", acceptsFaces: false, valueCents: 10260, costCents: 0 },
      { name: "Exérese ou Excisão de Rânula", acceptsFaces: false, valueCents: 44501, costCents: 13350 },
      { name: "Exodontia com Odonto-Secção", acceptsFaces: false, valueCents: 49098, costCents: 0 },
      { name: "Exodontia com Retalho", acceptsFaces: false, valueCents: 42054, costCents: 0 },
      { name: "Exodontia de Dentes Inclusos / Impactados", acceptsFaces: false, valueCents: 29795, costCents: 8938 },
      { name: "Exodontia de Dentes Semi-inclusos / impactados", acceptsFaces: false, valueCents: 31496, costCents: 0 },
      { name: "Exodontia de Permanente por Indicação Ortodôntica/protética", acceptsFaces: false, valueCents: 6574, costCents: 0 },
      { name: "Exodontia de Raiz Residual", acceptsFaces: false, valueCents: 5607, costCents: 1682 },
      { name: "Exodontia Simples de Decíduo", acceptsFaces: false, valueCents: 11187, costCents: 3356 },
      { name: "Exodontia Simples de Permanente", acceptsFaces: false, valueCents: 34314, costCents: 0 },
      { name: "Frenulectomia Lingual (Frenectomia)", acceptsFaces: false, valueCents: 38798, costCents: 0 },
      { name: "Frenulectonia Labial (Frenectomia)", acceptsFaces: false, valueCents: 15489, costCents: 4646 },
      { name: "Frenulotomia Labial (Frenotomia)", acceptsFaces: false, valueCents: 7001, costCents: 2100 },
      { name: "Frenulotomia Lingual (Frenotomia)", acceptsFaces: false, valueCents: 30789, costCents: 9236 },
      { name: "Punção Aspirativa", acceptsFaces: false, valueCents: 25398, costCents: 0 },
      { name: "Reconstrução de Sulco Gengivo-labial", acceptsFaces: false, valueCents: 46235, costCents: 13870 },
      { name: "Redução Cruenta de Fratura Alvéolo Dentária", acceptsFaces: false, valueCents: 18533, costCents: 5559 },
      { name: "Redução Incruenta de Fratura Alvéolo Dentária", acceptsFaces: false, valueCents: 47405, costCents: 14221 },
      { name: "Remoção de tumores intra ósseos", acceptsFaces: false, valueCents: 11644, costCents: 0 },
      { name: "Sepultamento Radicular", acceptsFaces: false, valueCents: 8534, costCents: 0 },
      { name: "Tracionamento Cirúrgico com Finalidade Ortodôntica", acceptsFaces: false, valueCents: 46643, costCents: 13992 },
      { name: "Tratamento Cirúrgico das Fístulas Buco-nasal", acceptsFaces: false, valueCents: 44274, costCents: 0 },
      { name: "Tratamento Cirúrgico das Fístulas Buco-sinusal", acceptsFaces: false, valueCents: 46769, costCents: 14030 },
      { name: "Tratamento Cirúrgico de Bridas Constritivas", acceptsFaces: false, valueCents: 15576, costCents: 0 },
      { name: "Tratamento Cirúrgico de Hiperplasias de Tecidos Moles", acceptsFaces: false, valueCents: 28733, costCents: 8619 },
      { name: "Tratamento Cirúrgico de Hiperplasias de Tecidos Ósseos", acceptsFaces: false, valueCents: 31983, costCents: 9594 },
      { name: "Tratamento Cirúrgico de Tumores Benignos de Tecidos Ósseos", acceptsFaces: false, valueCents: 14362, costCents: 0 },
      { name: "Tratamento Cirúrgico dos Tumores Benignos de Tecidos Moles", acceptsFaces: false, valueCents: 14882, costCents: 0 },
      { name: "Tratamento Cirúrgico para Tumores Odontogênicos Benignos", acceptsFaces: false, valueCents: 21561, costCents: 6468 },
      { name: "Tratamento Conservador de Luxação de ATM", acceptsFaces: false, valueCents: 43528, costCents: 0 },
      { name: "Ulectomia", acceptsFaces: false, valueCents: 23873, costCents: 7161 },
      { name: "Ulotomia", acceptsFaces: false, valueCents: 29214, costCents: 0 },
    ],
  },
  {
    name: "Dentística",
    treatments: [
      { name: "Clareamento de Dente Desvitalizado", acceptsFaces: false, valueCents: 35263, costCents: 10578 },
      { name: "Clareamento Dentário Caseiro", acceptsFaces: false, valueCents: 40670, costCents: 0 },
      { name: "Clareamento em Consultório", acceptsFaces: false, valueCents: 7236, costCents: 0 },
      { name: "Faceta em Resina Fotopolimerizável", acceptsFaces: false, valueCents: 22551, costCents: 6765 },
      { name: "Núcleo de Preenchimento", acceptsFaces: false, valueCents: 17021, costCents: 5106 },
      { name: "Placa de Clareamento", acceptsFaces: true, valueCents: 40618, costCents: 0 },
      { name: "Restauração Atraumática em Dente Decíduo", acceptsFaces: true, valueCents: 10281, costCents: 3084 },
      { name: "Restauração Atraumática em Dente Permanente", acceptsFaces: true, valueCents: 6491, costCents: 1947 },
      { name: "Restauração de Amálgama - 1 face", acceptsFaces: true, valueCents: 44087, costCents: 13226 },
      { name: "Restauração de Amálgama - 2 faces", acceptsFaces: true, valueCents: 44102, costCents: 0 },
      { name: "Restauração de Amálgama - 3 faces", acceptsFaces: true, valueCents: 13683, costCents: 4104 },
      { name: "Restauração de Amálgama - 4 faces", acceptsFaces: true, valueCents: 10099, costCents: 3029 },
      { name: "Restauração em Ionômero de Vidro - 1 face", acceptsFaces: true, valueCents: 18645, costCents: 5593 },
      { name: "Restauração em Ionômero de Vidro - 2 faces", acceptsFaces: true, valueCents: 7843, costCents: 2352 },
      { name: "Restauração em Ionômero de Vidro - 3 faces", acceptsFaces: true, valueCents: 27137, costCents: 8141 },
      { name: "Restauração em Ionômero de Vidro - 4 faces", acceptsFaces: true, valueCents: 18651, costCents: 5595 },
      { name: "Restauração em Resina Fotopolimerizável 1 face", acceptsFaces: true, valueCents: 32749, costCents: 9824 },
      { name: "Restauração em Resina Fotopolimerizável 2 faces", acceptsFaces: true, valueCents: 46676, costCents: 0 },
      { name: "Restauração em Resina Fotopolimerizável 3 faces", acceptsFaces: true, valueCents: 47797, costCents: 14339 },
      { name: "Restauração em Resina Fotopolimerizável 4 faces", acceptsFaces: true, valueCents: 22370, costCents: 0 },
      { name: "Restauração Temporária (Expectante)", acceptsFaces: true, valueCents: 37108, costCents: 0 },
    ],
  },
  {
    name: "Disfunção Temporomandibular (DTM)",
    treatments: [
    ],
  },
  {
    name: "Endodontia",
    treatments: [
      { name: "Capeamento Pulpar Direto", acceptsFaces: false, valueCents: 36102, costCents: 0 },
      { name: "Curativo de Demora", acceptsFaces: false, valueCents: 41749, costCents: 12524 },
      { name: "Preparo para Núcleo Intrarradicular", acceptsFaces: false, valueCents: 44357, costCents: 13307 },
      { name: "Pulpectomia", acceptsFaces: false, valueCents: 25921, costCents: 7776 },
      { name: "Pulpotomia", acceptsFaces: false, valueCents: 37985, costCents: 11395 },
      { name: "Pulpotomia em dente decíduo", acceptsFaces: false, valueCents: 42757, costCents: 12827 },
      { name: "Remoção de Corpo Estranho Intra-Canal", acceptsFaces: false, valueCents: 39024, costCents: 0 },
      { name: "Remoção de Material Obturador", acceptsFaces: false, valueCents: 13974, costCents: 0 },
      { name: "Remoção de Núcleo Intra-Radicular", acceptsFaces: false, valueCents: 21389, costCents: 6416 },
      { name: "Remoção de Trabalho Protético", acceptsFaces: false, valueCents: 7317, costCents: 2195 },
      { name: "Retratamento Endodôntico Birradicular", acceptsFaces: false, valueCents: 43036, costCents: 0 },
      { name: "Retratamento Endodôntico Multirradicular", acceptsFaces: false, valueCents: 30973, costCents: 9291 },
      { name: "Retratamento Endodôntico Unirradicular", acceptsFaces: false, valueCents: 32487, costCents: 9746 },
      { name: "Tratamento de Perfuração Endodôntica", acceptsFaces: false, valueCents: 25558, costCents: 0 },
      { name: "Tratamento Endodôntico Birradicular", acceptsFaces: false, valueCents: 34735, costCents: 10420 },
      { name: "Tratamento Endodôntico de Dente com Rizogênese Incompleta", acceptsFaces: false, valueCents: 11584, costCents: 0 },
      { name: "Tratamento Endodôntico em Dente Decíduo", acceptsFaces: false, valueCents: 41782, costCents: 0 },
      { name: "Tratamento Endodôntico Multirradicular", acceptsFaces: false, valueCents: 46419, costCents: 13925 },
      { name: "Tratamento Endodôntico Unirradicular", acceptsFaces: false, valueCents: 49824, costCents: 0 },
    ],
  },
  {
    name: "Estética",
    treatments: [
    ],
  },
  {
    name: "Harmonização Facial",
    treatments: [
      { name: "Bichectomia", acceptsFaces: false, valueCents: 24777, costCents: 7433 },
      { name: "Bioestimulador de colágeno", acceptsFaces: false, valueCents: 22179, costCents: 6653 },
      { name: "Fios de PDO liso", acceptsFaces: false, valueCents: 43002, costCents: 0 },
      { name: "Fios de sustentação (espiculado)", acceptsFaces: false, valueCents: 8590, costCents: 0 },
      { name: "Lipo de papada cirúrgica", acceptsFaces: false, valueCents: 28703, costCents: 8610 },
      { name: "Lipo de papada enzimática", acceptsFaces: false, valueCents: 16446, costCents: 0 },
      { name: "MD codes", acceptsFaces: false, valueCents: 38264, costCents: 0 },
      { name: "Microagulhamento", acceptsFaces: false, valueCents: 34256, costCents: 0 },
      { name: "Preenchimento de malar", acceptsFaces: false, valueCents: 23262, costCents: 0 },
      { name: "Preenchimento de mandíbula", acceptsFaces: false, valueCents: 45893, costCents: 13767 },
      { name: "Preenchimento de mento", acceptsFaces: false, valueCents: 34299, costCents: 10289 },
      { name: "Preenchimento de olheiras", acceptsFaces: false, valueCents: 48341, costCents: 14502 },
      { name: "Preenchimento de sulco labiomentoniano (marionete)", acceptsFaces: false, valueCents: 24226, costCents: 0 },
      { name: "Preenchimento do sulco nasogeniano (bigode chinês)", acceptsFaces: false, valueCents: 48380, costCents: 0 },
      { name: "Preenchimento em fossa canina", acceptsFaces: false, valueCents: 24096, costCents: 0 },
      { name: "Preenchimento labial", acceptsFaces: false, valueCents: 32170, costCents: 0 },
      { name: "Preenchimento nas têmporas", acceptsFaces: false, valueCents: 10216, costCents: 0 },
      { name: "Skinbooster", acceptsFaces: false, valueCents: 46343, costCents: 13902 },
      { name: "Subcision", acceptsFaces: false, valueCents: 23869, costCents: 7160 },
      { name: "Toxina botulínica (botox)", acceptsFaces: false, valueCents: 22893, costCents: 6867 },
    ],
  },
  {
    name: "Implantodontia",
    treatments: [
      { name: "Cirurgia Odontológica com Aplicação de Aloenxertos", acceptsFaces: false, valueCents: 22791, costCents: 6837 },
      { name: "Coroa Provisória sobre Implante", acceptsFaces: false, valueCents: 8444, costCents: 0 },
      { name: "Coroa Total Livre de Metal (metal free) sobre Iimplante", acceptsFaces: false, valueCents: 13849, costCents: 4154 },
      { name: "Coroa Total Metalo Cerâmica sobre Implante", acceptsFaces: false, valueCents: 28039, costCents: 8411 },
      { name: "Coroa Total Metalo Plástica sobre Implante", acceptsFaces: false, valueCents: 42200, costCents: 0 },
      { name: "Guia Cirúrgico para Implante", acceptsFaces: false, valueCents: 30887, costCents: 9266 },
      { name: "Implante Ortodôntico", acceptsFaces: false, valueCents: 24658, costCents: 0 },
      { name: "Instalação de cicatrizador", acceptsFaces: false, valueCents: 6322, costCents: 0 },
      { name: "Instalação de conexão de prótese cimentada", acceptsFaces: false, valueCents: 13799, costCents: 4139 },
      { name: "Instalação de conexão de prótese parafusada", acceptsFaces: false, valueCents: 13918, costCents: 0 },
      { name: "Instalação de implante cone morse", acceptsFaces: false, valueCents: 17052, costCents: 0 },
      { name: "Instalação de implante hexágono externo", acceptsFaces: false, valueCents: 35619, costCents: 10685 },
      { name: "Instalação de implante hexágono interno", acceptsFaces: false, valueCents: 30666, costCents: 0 },
      { name: "Instalação de Implante Ósseo Integrado", acceptsFaces: false, valueCents: 46134, costCents: 0 },
      { name: "Levantamento de seio", acceptsFaces: false, valueCents: 49726, costCents: 0 },
      { name: "Levantamento de seio atraumático", acceptsFaces: false, valueCents: 41855, costCents: 12556 },
      { name: "Prótese parcial removível implanto suportada", acceptsFaces: false, valueCents: 28197, costCents: 8459 },
      { name: "Prótese total removível implanto suportada", acceptsFaces: false, valueCents: 49882, costCents: 0 },
      { name: "Protocolo inferior", acceptsFaces: false, valueCents: 14553, costCents: 4365 },
      { name: "Protocolo superior", acceptsFaces: false, valueCents: 32219, costCents: 9665 },
    ],
  },
  {
    name: "Odontopediatria",
    treatments: [
    ],
  },
  {
    name: "Ortodontia",
    treatments: [
      { name: "Aparelho Extra Bucal", acceptsFaces: false, valueCents: 10926, costCents: 0 },
      { name: "Aparelho Ortodôntico Fixo Metálico", acceptsFaces: false, valueCents: 34285, costCents: 10285 },
      { name: "Aparelho Ortodôntico Fixo metálico Parcial", acceptsFaces: false, valueCents: 10512, costCents: 0 },
      { name: "Arco Lingual", acceptsFaces: false, valueCents: 22018, costCents: 0 },
      { name: "Bionator de Balters", acceptsFaces: false, valueCents: 38704, costCents: 0 },
      { name: "Contenção Fixa", acceptsFaces: false, valueCents: 21352, costCents: 0 },
      { name: "Disjuntor Palatino (Hirax)", acceptsFaces: false, valueCents: 13088, costCents: 0 },
      { name: "Disjuntor Palatino (Macnamara)", acceptsFaces: false, valueCents: 19319, costCents: 5795 },
      { name: "Grade Palatina Fixa", acceptsFaces: false, valueCents: 47786, costCents: 0 },
      { name: "Grade Palatina Removível", acceptsFaces: false, valueCents: 30071, costCents: 9021 },
      { name: "Manutenção de Aparelho Ortodôntico Fixo", acceptsFaces: false, valueCents: 46447, costCents: 13934 },
      { name: "Manutenção de Aparelho Ortodôntico Removível", acceptsFaces: false, valueCents: 49694, costCents: 0 },
      { name: "Mascara Facial Delaire e Tração Reversa", acceptsFaces: false, valueCents: 8592, costCents: 0 },
      { name: "Mentoneira", acceptsFaces: false, valueCents: 8728, costCents: 0 },
      { name: "Placa de Haley", acceptsFaces: false, valueCents: 24272, costCents: 0 },
      { name: "Placa de Haley com torno expansor", acceptsFaces: false, valueCents: 43552, costCents: 0 },
      { name: "Placa de Mordida Ortodôntica", acceptsFaces: false, valueCents: 27623, costCents: 8286 },
      { name: "Placa Labio-ativa (Lip bumper)", acceptsFaces: false, valueCents: 16910, costCents: 0 },
      { name: "Plano Inclinado", acceptsFaces: false, valueCents: 14792, costCents: 0 },
      { name: "Quadri-Hélice", acceptsFaces: false, valueCents: 15896, costCents: 0 },
      { name: "Tratamento Ortodôntico com Alinhadores (aligners)", acceptsFaces: false, valueCents: 47709, costCents: 14312 },
    ],
  },
  {
    name: "Ortopedia Funcional",
    treatments: [
    ],
  },
  {
    name: "Outros",
    treatments: [
      { name: "Condicionamento em Odontologia", acceptsFaces: false, valueCents: 26447, costCents: 7934 },
      { name: "Condicionamento em Odontologia para pacientes especiais", acceptsFaces: false, valueCents: 38123, costCents: 11436 },
      { name: "Consulta de Auditoria - perícia final", acceptsFaces: false, valueCents: 29197, costCents: 8759 },
      { name: "Consulta de Auditoria - perícia inicial", acceptsFaces: false, valueCents: 38866, costCents: 0 },
      { name: "Consulta de Retorno", acceptsFaces: false, valueCents: 10329, costCents: 3098 },
      { name: "Consulta Inicial", acceptsFaces: false, valueCents: 42231, costCents: 12669 },
      { name: "Consulta odontológica", acceptsFaces: false, valueCents: 39255, costCents: 11776 },
      { name: "Falta a Consulta", acceptsFaces: false, valueCents: 24783, costCents: 7434 },
    ],
  },
  {
    name: "Periodontia",
    treatments: [
      { name: "Ajuste Oclusal por Acréscimo", acceptsFaces: false, valueCents: 21820, costCents: 0 },
      { name: "Ajuste Oclusal por desgaste", acceptsFaces: false, valueCents: 24271, costCents: 7281 },
      { name: "Aumento de Coroa Clínica", acceptsFaces: false, valueCents: 14436, costCents: 0 },
      { name: "Cirurgia Periodontal com Retalho", acceptsFaces: false, valueCents: 19904, costCents: 0 },
      { name: "Cunha Proximal", acceptsFaces: false, valueCents: 42049, costCents: 12614 },
      { name: "Enxerto com Osso Liofilizado", acceptsFaces: false, valueCents: 19301, costCents: 5790 },
      { name: "Enxerto Gengival Livre", acceptsFaces: false, valueCents: 37036, costCents: 0 },
      { name: "Enxerto Pediculado", acceptsFaces: false, valueCents: 43105, costCents: 12931 },
      { name: "Gengivectomia", acceptsFaces: false, valueCents: 28424, costCents: 0 },
      { name: "Gengivoplastia", acceptsFaces: false, valueCents: 19695, costCents: 5908 },
      { name: "Placa de mordida miorelaxante", acceptsFaces: false, valueCents: 8004, costCents: 0 },
      { name: "Raspagem Sub-gengival (RASUB)", acceptsFaces: false, valueCents: 27988, costCents: 0 },
      { name: "Raspagem Supra-gengival (RAP) - Limpeza", acceptsFaces: false, valueCents: 39107, costCents: 11732 },
      { name: "Remoção dos Fatores de Retenção de Placa Bacteriana", acceptsFaces: false, valueCents: 20220, costCents: 0 },
      { name: "Tratamento de Fluorose - microabrasão", acceptsFaces: false, valueCents: 28153, costCents: 8445 },
      { name: "Tratamento de Gengivite Necrosante Aguda (GNA)", acceptsFaces: false, valueCents: 28992, costCents: 0 },
      { name: "Tratamento de Pericoronarite", acceptsFaces: false, valueCents: 48795, costCents: 14638 },
      { name: "Tunelização", acceptsFaces: false, valueCents: 23865, costCents: 7159 },
    ],
  },
  {
    name: "Prevenção",
    treatments: [
      { name: "Aplicação de Cariostático", acceptsFaces: false, valueCents: 23019, costCents: 6905 },
      { name: "Aplicação de Selante de Fóssulas e Fissuras", acceptsFaces: false, valueCents: 40062, costCents: 0 },
      { name: "Aplicação Tópica de Flúor", acceptsFaces: false, valueCents: 42947, costCents: 12884 },
      { name: "Aplicação Tópica de Verniz Fluoretado", acceptsFaces: false, valueCents: 29503, costCents: 8850 },
      { name: "Atividade Educativa em Saúde Bucal", acceptsFaces: false, valueCents: 13924, costCents: 0 },
      { name: "Atividade Educativa para Pais e/ou Cuidadores", acceptsFaces: false, valueCents: 8761, costCents: 2628 },
      { name: "Atividade Educativa para Pais e/ou Cuidadores de pacientes Especiais", acceptsFaces: false, valueCents: 18572, costCents: 0 },
      { name: "Controle de Biofilme (Placa Bacteriana)", acceptsFaces: false, valueCents: 44633, costCents: 13389 },
      { name: "Dessensibilização Dentária", acceptsFaces: false, valueCents: 37641, costCents: 11292 },
      { name: "Mantenedor de espaço fixo", acceptsFaces: false, valueCents: 8819, costCents: 2645 },
      { name: "Mantenedor de espaço removível", acceptsFaces: false, valueCents: 41033, costCents: 12309 },
      { name: "Profilaxia + Polimento Coronário - Limpeza", acceptsFaces: false, valueCents: 26863, costCents: 8058 },
      { name: "Remineralização Dentária", acceptsFaces: false, valueCents: 33270, costCents: 0 },
    ],
  },
  {
    name: "Prótese",
    treatments: [
      { name: "Coroa de Acetato", acceptsFaces: false, valueCents: 18693, costCents: 5607 },
      { name: "Coroa de Acetato em Dente Decíduo", acceptsFaces: false, valueCents: 49701, costCents: 14910 },
      { name: "Coroa de Aço", acceptsFaces: false, valueCents: 30389, costCents: 9116 },
      { name: "Coroa de Aço em Dente Decíduo", acceptsFaces: false, valueCents: 9939, costCents: 2981 },
      { name: "Coroa de Policarbonato", acceptsFaces: false, valueCents: 38834, costCents: 0 },
      { name: "Coroa de Policarbonato em Dente Decíduo", acceptsFaces: false, valueCents: 17660, costCents: 0 },
      { name: "Coroa Provisória com Pino", acceptsFaces: false, valueCents: 49852, costCents: 0 },
      { name: "Coroa Provisória sem Pino", acceptsFaces: false, valueCents: 34844, costCents: 0 },
      { name: "Coroa Total Acrílica Prensada", acceptsFaces: false, valueCents: 24356, costCents: 0 },
      { name: "Coroa Total em Cerâmica Pura", acceptsFaces: false, valueCents: 14997, costCents: 4499 },
      { name: "Coroa Total em Cerômero", acceptsFaces: false, valueCents: 23751, costCents: 7125 },
      { name: "Coroa Total Metálica", acceptsFaces: false, valueCents: 25275, costCents: 7582 },
      { name: "Coroa Total Metalo Cerâmica", acceptsFaces: false, valueCents: 22067, costCents: 6620 },
      { name: "Coroa Total Metalo-Plástica", acceptsFaces: false, valueCents: 10552, costCents: 0 },
      { name: "Faceta em Cerâmica Pura", acceptsFaces: false, valueCents: 9604, costCents: 0 },
      { name: "Faceta em Cerômero", acceptsFaces: false, valueCents: 36073, costCents: 10821 },
      { name: "Guia Cirúrgico para Prótese Imediata", acceptsFaces: false, valueCents: 44226, costCents: 0 },
      { name: "Núcleo Metálico Fundido", acceptsFaces: false, valueCents: 23198, costCents: 0 },
      { name: "Pino Pré Fabricado", acceptsFaces: false, valueCents: 10832, costCents: 0 },
      { name: "Prótese Fixa Adesiva Direta (provisória)", acceptsFaces: false, valueCents: 5852, costCents: 0 },
      { name: "Prótese Fixa Adesiva em Cerômero (metal free)", acceptsFaces: false, valueCents: 30814, costCents: 0 },
      { name: "Prótese Fixa Adesiva Indireta em Metálo Cerâmica 3 elementos", acceptsFaces: false, valueCents: 33954, costCents: 0 },
      { name: "Prótese Fixa Adesiva Indireta em Metalo-Plástica 3 elementos", acceptsFaces: false, valueCents: 30289, costCents: 9086 },
      { name: "Prótese Parcial Fixa em Metálo Cerâmica", acceptsFaces: false, valueCents: 45812, costCents: 0 },
      { name: "Prótese Parcial Fixa em Metálo Plástica", acceptsFaces: false, valueCents: 5136, costCents: 0 },
      { name: "Prótese Parcial Removível com Encaixes (PPR)", acceptsFaces: false, valueCents: 39098, costCents: 0 },
      { name: "Prótese Parcial Removível com Grampos Bilateral (PPR)", acceptsFaces: false, valueCents: 30661, costCents: 9198 },
      { name: "Prótese Parcial Removível Provisória (PPR)", acceptsFaces: false, valueCents: 39972, costCents: 0 },
      { name: "Prótese Total Imediata (PT)", acceptsFaces: false, valueCents: 9028, costCents: 0 },
      { name: "Prótese Total Incolor (PT)", acceptsFaces: false, valueCents: 19819, costCents: 5945 },
    ],
  },
  {
    name: "Radiologia",
    treatments: [
      { name: "Fotografia - Unidade", acceptsFaces: false, valueCents: 17108, costCents: 0 },
      { name: "Levantamento Radiográfico", acceptsFaces: false, valueCents: 22370, costCents: 0 },
      { name: "Modelos Ortodônticos- Par", acceptsFaces: false, valueCents: 33363, costCents: 10008 },
      { name: "Radiografia da Mão (Carpal)", acceptsFaces: false, valueCents: 27900, costCents: 0 },
      { name: "Radiografia de ATM", acceptsFaces: false, valueCents: 44329, costCents: 13298 },
      { name: "Radiografia Interproximal - Bite-Wing", acceptsFaces: false, valueCents: 12761, costCents: 3828 },
      { name: "Radiografia Oclusal", acceptsFaces: false, valueCents: 44190, costCents: 0 },
      { name: "Radiografia Panorâmica", acceptsFaces: false, valueCents: 7255, costCents: 2176 },
      { name: "Radiografia Panorâmica com Traçado Cefalométrico", acceptsFaces: false, valueCents: 15744, costCents: 0 },
      { name: "Radiografia Periapical", acceptsFaces: false, valueCents: 37277, costCents: 11183 },
      { name: "Radiografia póstero-anterior", acceptsFaces: false, valueCents: 34387, costCents: 10316 },
      { name: "Teleradiografia com Traçado", acceptsFaces: false, valueCents: 38030, costCents: 0 },
      { name: "Teleradiografia sem Traçado", acceptsFaces: false, valueCents: 30393, costCents: 9117 },
      { name: "Tomografia", acceptsFaces: false, valueCents: 32233, costCents: 9669 },
      { name: "Traçado Cefalométrico", acceptsFaces: false, valueCents: 18038, costCents: 0 },
    ],
  },
  {
    name: "Testes e Exames Laboratoriais",
    treatments: [
      { name: "Diagnóstico Anatomopatológico em Citologia Esfoliativa", acceptsFaces: false, valueCents: 11117, costCents: 3335 },
      { name: "Diagnóstico Anatomopatológico em Material de Biópsia", acceptsFaces: false, valueCents: 14757, costCents: 4427 },
      { name: "Diagnóstico Anatomopatológico em Peça Cirurgica", acceptsFaces: false, valueCents: 14283, costCents: 4284 },
      { name: "Diagnóstico Anatomopatológico em Punção", acceptsFaces: false, valueCents: 34409, costCents: 10322 },
      { name: "Diagnóstico por Meio de Enceramento", acceptsFaces: false, valueCents: 16782, costCents: 0 },
      { name: "Teste de Fluxo Salivar", acceptsFaces: false, valueCents: 18274, costCents: 0 },
      { name: "Teste de PH da Saliva", acceptsFaces: false, valueCents: 44436, costCents: 0 },
    ],
  },
  {
    name: "Urgência",
    treatments: [
      { name: "Colagem de Fragmentos Dentários", acceptsFaces: true, valueCents: 38523, costCents: 11556 },
      { name: "Consulta Odontológica de Urgência", acceptsFaces: false, valueCents: 47210, costCents: 0 },
      { name: "Consulta Odontológica de Urgência 24 horas", acceptsFaces: false, valueCents: 25902, costCents: 0 },
      { name: "Controle de Hemorragia com Aplicação de Agente Hemostático", acceptsFaces: false, valueCents: 33948, costCents: 0 },
      { name: "Controle de Hemorragia sem Aplicação de Agente Hemostático", acceptsFaces: false, valueCents: 31959, costCents: 9587 },
      { name: "Imobilização Dentária em Dentes Decíduos", acceptsFaces: false, valueCents: 33826, costCents: 0 },
      { name: "Imobilização Dentária em Dentes Permanentes", acceptsFaces: false, valueCents: 23927, costCents: 7178 },
      { name: "Incisão e Drenagem Extra Oral de Abscesso", acceptsFaces: false, valueCents: 33238, costCents: 0 },
      { name: "Incisão e Drenagem Intra Oral de Abscesso", acceptsFaces: false, valueCents: 26898, costCents: 0 },
      { name: "Recimentação de Trabalhos Protéticos", acceptsFaces: false, valueCents: 34405, costCents: 10321 },
      { name: "Redução Simples de Luxação de ATM", acceptsFaces: false, valueCents: 29043, costCents: 8712 },
      { name: "Reimplante Dentário com Contenção", acceptsFaces: false, valueCents: 32573, costCents: 9771 },
      { name: "Sutura de Ferida", acceptsFaces: false, valueCents: 35337, costCents: 10601 },
      { name: "Tratamento de Abscesso Periodontal agudo", acceptsFaces: false, valueCents: 34356, costCents: 0 },
      { name: "Tratamento de Alveolite", acceptsFaces: false, valueCents: 40725, costCents: 12217 },
    ],
  },
];

