services:
  nginx:
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_certs:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt

volumes:
  certbot_www:
    name: aplopes_certbot_www
  certbot_certs:
    name: aplopes_certbot_certs
