parent=keycloak.v3
locales=pt
darkMode=false
contentHashPattern=assets/.*

title=Minha conta Citybox
description=Console para gerenciar seus dados de acesso na plataforma Citybox.
logo=img/aplopes-logo.svg
logoUrl=https://backoffice.citybox.com
favIcon=/img/aplopes-favicon.svg
favIconType=image/svg+xml

styles=css/citybox-account.css
