/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param label 
 * @param zipCode 
 * @param street 
 * @param number 
 * @param neighborhood 
 * @param city 
 * @param state 
 * @param complement 
 * @param isDefault 
 */


data class AddressInput (

    @SerializedName("label")
    val label: kotlin.String,

    @SerializedName("zipCode")
    val zipCode: kotlin.String,

    @SerializedName("street")
    val street: kotlin.String,

    @SerializedName("number")
    val number: kotlin.String,

    @SerializedName("neighborhood")
    val neighborhood: kotlin.String,

    @SerializedName("city")
    val city: kotlin.String,

    @SerializedName("state")
    val state: kotlin.String,

    @SerializedName("complement")
    val complement: kotlin.String? = null,

    @SerializedName("isDefault")
    val isDefault: kotlin.Boolean? = null

) {


}

