/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Review

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param photoUrl 
 * @param review 
 */


data class AddReviewPhoto201ResponseData (

    @SerializedName("photoUrl")
    val photoUrl: java.net.URI? = null,

    @SerializedName("review")
    val review: Review? = null

) {


}

