/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.Cart
import com.citybox.api.models.CheckoutPreview

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param appliedCoupon 
 * @param cart 
 * @param preview 
 */


data class ApplyCartCoupon200ResponseData (

    @SerializedName("appliedCoupon")
    val appliedCoupon: AppliedCoupon? = null,

    @SerializedName("cart")
    val cart: Cart? = null,

    @SerializedName("preview")
    val preview: CheckoutPreview? = null

) {


}

