/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CouponType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code 
 * @param type 
 * @param `value` 
 * @param discountAmount 
 */


data class AppliedCoupon (

    @SerializedName("code")
    val code: kotlin.String? = null,

    @SerializedName("type")
    val type: CouponType? = null,

    @SerializedName("value")
    val `value`: java.math.BigDecimal? = null,

    @SerializedName("discountAmount")
    val discountAmount: java.math.BigDecimal? = null

) {


}

