/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.User

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param expiresIn 
 * @param user 
 */


data class AuthEnvelopeData (

    @SerializedName("accessToken")
    val accessToken: kotlin.String? = null,

    @SerializedName("refreshToken")
    val refreshToken: kotlin.String? = null,

    @SerializedName("expiresIn")
    val expiresIn: kotlin.Int? = null,

    @SerializedName("user")
    val user: User? = null

) {


}

