/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param isActive 
 * @param cancelledAt 
 * @param accessUntil 
 */


data class CancelSubscription200ResponseData (

    @SerializedName("isActive")
    val isActive: kotlin.Boolean? = null,

    @SerializedName("cancelledAt")
    val cancelledAt: java.time.OffsetDateTime? = null,

    @SerializedName("accessUntil")
    val accessUntil: java.time.LocalDate? = null

) {


}

