/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.CartItem
import com.citybox.api.models.CartShippingPreview

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param items 
 * @param itemCount 
 * @param subtotal 
 * @param appliedCoupon 
 * @param couponDiscount 
 * @param shippingPreview 
 */


data class Cart (

    @SerializedName("items")
    val items: kotlin.collections.List<CartItem>? = null,

    @SerializedName("itemCount")
    val itemCount: kotlin.Int? = null,

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @SerializedName("appliedCoupon")
    val appliedCoupon: AppliedCoupon? = null,

    @SerializedName("couponDiscount")
    val couponDiscount: java.math.BigDecimal? = null,

    @SerializedName("shippingPreview")
    val shippingPreview: CartShippingPreview? = null

) {


}

