/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param selectedOptionId 
 * @param price 
 * @param freeShippingMessage 
 */


data class CartShippingPreview (

    @SerializedName("selectedOptionId")
    val selectedOptionId: kotlin.String? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null,

    @SerializedName("freeShippingMessage")
    val freeShippingMessage: kotlin.String? = null

) {


}

