/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param text 
 * @param isAgent 
 * @param time 
 */


data class ChatMessage (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("isAgent")
    val isAgent: kotlin.Boolean? = null,

    @SerializedName("time")
    val time: java.time.OffsetDateTime? = null

) {


}

