/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subtotal 
 * @param shipping 
 * @param couponDiscount 
 * @param pixDiscount 
 * @param total 
 */


data class CheckoutPreview (

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @SerializedName("shipping")
    val shipping: java.math.BigDecimal? = null,

    @SerializedName("couponDiscount")
    val couponDiscount: java.math.BigDecimal? = null,

    @SerializedName("pixDiscount")
    val pixDiscount: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null

) {


}

