/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param count 
 * @param `value` 
 * @param hasInterest 
 */


data class CheckoutPreview200ResponseDataAllOfInstallmentOptionsInner (

    @SerializedName("count")
    val count: kotlin.Int? = null,

    @SerializedName("value")
    val `value`: java.math.BigDecimal? = null,

    @SerializedName("hasInterest")
    val hasInterest: kotlin.Boolean? = null

) {


}

