/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CheckoutPreview200ResponseDataAllOfInstallmentOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subtotal 
 * @param shipping 
 * @param couponDiscount 
 * @param pixDiscount 
 * @param total 
 * @param pixDiscountPercent 
 * @param installmentOptions 
 * @param canConfirm 
 * @param validationErrors 
 */


data class CheckoutPreview200ResponseData (

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @SerializedName("shipping")
    val shipping: java.math.BigDecimal? = null,

    @SerializedName("couponDiscount")
    val couponDiscount: java.math.BigDecimal? = null,

    @SerializedName("pixDiscount")
    val pixDiscount: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null,

    @SerializedName("pixDiscountPercent")
    val pixDiscountPercent: kotlin.Int? = null,

    @SerializedName("installmentOptions")
    val installmentOptions: kotlin.collections.List<CheckoutPreview200ResponseDataAllOfInstallmentOptionsInner>? = null,

    @SerializedName("canConfirm")
    val canConfirm: kotlin.Boolean? = null,

    @SerializedName("validationErrors")
    val validationErrors: kotlin.collections.List<kotlin.String>? = null

) {


}

