/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.AppliedCoupon
import com.citybox.api.models.PaymentType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param selectedAddressId 
 * @param shippingOptionId 
 * @param appliedCoupon 
 * @param paymentType 
 * @param paymentMethodId 
 * @param boletoCpf 
 * @param canConfirm 
 */


data class CheckoutSession (

    @SerializedName("selectedAddressId")
    val selectedAddressId: kotlin.String? = null,

    @SerializedName("shippingOptionId")
    val shippingOptionId: kotlin.String? = null,

    @SerializedName("appliedCoupon")
    val appliedCoupon: AppliedCoupon? = null,

    @SerializedName("paymentType")
    val paymentType: PaymentType? = null,

    @SerializedName("paymentMethodId")
    val paymentMethodId: kotlin.String? = null,

    @SerializedName("boletoCpf")
    val boletoCpf: kotlin.String? = null,

    @SerializedName("canConfirm")
    val canConfirm: kotlin.Boolean? = null

) {


}

