/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CouponType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code 
 * @param description 
 * @param type 
 * @param `value` 
 * @param expiry 
 * @param isApplicable 
 * @param reason 
 */


data class Coupon (

    @SerializedName("code")
    val code: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("type")
    val type: CouponType? = null,

    @SerializedName("value")
    val `value`: java.math.BigDecimal? = null,

    @SerializedName("expiry")
    val expiry: java.time.LocalDate? = null,

    @SerializedName("isApplicable")
    val isApplicable: kotlin.Boolean? = null,

    @SerializedName("reason")
    val reason: kotlin.String? = null

) {


}

