/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rating 
 * @param text 
 * @param orderId 
 * @param photoUrls 
 */


data class CreateReviewRequest (

    @SerializedName("rating")
    val rating: kotlin.Int,

    @SerializedName("text")
    val text: kotlin.String,

    @SerializedName("orderId")
    val orderId: kotlin.String? = null,

    @SerializedName("photoUrls")
    val photoUrls: kotlin.collections.List<java.net.URI>? = null

) {


}

