/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CartItemInput
import com.citybox.api.models.PaymentInput

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param payment 
 * @param addressId 
 * @param shippingOptionId 
 * @param couponCode 
 * @param items 
 * @param buyNow 
 */


data class CreateOrderRequest (

    @SerializedName("payment")
    val payment: PaymentInput,

    @SerializedName("addressId")
    val addressId: kotlin.String? = null,

    @SerializedName("shippingOptionId")
    val shippingOptionId: kotlin.String? = null,

    @SerializedName("couponCode")
    val couponCode: kotlin.String? = null,

    @SerializedName("items")
    val items: kotlin.collections.List<CartItemInput>? = null,

    @SerializedName("buyNow")
    val buyNow: kotlin.Boolean? = false

) {


}

