/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param number 
 * @param holderName 
 * @param expiry 
 * @param cvv 
 * @param label 
 * @param isDefault 
 */


data class CreatePaymentMethodRequest (

    @SerializedName("number")
    val number: kotlin.String,

    @SerializedName("holderName")
    val holderName: kotlin.String,

    @SerializedName("expiry")
    val expiry: kotlin.String,

    @SerializedName("cvv")
    val cvv: kotlin.String,

    @SerializedName("label")
    val label: kotlin.String? = null,

    @SerializedName("isDefault")
    val isDefault: kotlin.Boolean? = null

) {


}

