/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Order
import com.citybox.api.models.PaymentResult

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param order 
 * @param payment 
 */


data class CreateOrder201ResponseData (

    @SerializedName("order")
    val order: Order? = null,

    @SerializedName("payment")
    val payment: PaymentResult? = null

) {


}

