/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.ErrorEnvelopeErrorsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param errors 
 */


data class ErrorEnvelope (

    @SerializedName("data")
    val `data`: kotlin.Any? = null,

    @SerializedName("errors")
    val errors: kotlin.collections.List<ErrorEnvelopeErrorsInner>? = null

) {


}

