/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.GetBanners200ResponseDataBannersInnerAction

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param title 
 * @param imageUrl 
 * @param action 
 */


data class GetBanners200ResponseDataBannersInner (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("imageUrl")
    val imageUrl: java.net.URI? = null,

    @SerializedName("action")
    val action: GetBanners200ResponseDataBannersInnerAction? = null

) {


}

