/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Category
import com.citybox.api.models.Product

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param category 
 * @param products 
 */


data class GetCategoryProducts200ResponseData (

    @SerializedName("category")
    val category: Category? = null,

    @SerializedName("products")
    val products: kotlin.collections.List<Product>? = null

) {


}

