/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.GetFiltersMetadata200ResponseDataFlagsInner
import com.citybox.api.models.GetFiltersMetadata200ResponseDataPriceRange
import com.citybox.api.models.GetFiltersMetadata200ResponseDataSortOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param brands 
 * @param priceRange 
 * @param sortOptions 
 * @param ratingOptions 
 * @param flags 
 */


data class GetFiltersMetadata200ResponseData (

    @SerializedName("brands")
    val brands: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("priceRange")
    val priceRange: GetFiltersMetadata200ResponseDataPriceRange? = null,

    @SerializedName("sortOptions")
    val sortOptions: kotlin.collections.List<GetFiltersMetadata200ResponseDataSortOptionsInner>? = null,

    @SerializedName("ratingOptions")
    val ratingOptions: kotlin.collections.List<java.math.BigDecimal>? = null,

    @SerializedName("flags")
    val flags: kotlin.collections.List<GetFiltersMetadata200ResponseDataFlagsInner>? = null

) {


}

