/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param invoiceUrl 
 * @param nfKey 
 * @param issuedAt 
 */


data class GetInvoice200ResponseData (

    @SerializedName("invoiceUrl")
    val invoiceUrl: java.net.URI? = null,

    @SerializedName("nfKey")
    val nfKey: kotlin.String? = null,

    @SerializedName("issuedAt")
    val issuedAt: java.time.OffsetDateTime? = null

) {


}

