/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Product

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param product 
 * @param installmentCount 
 * @param installmentValue 
 */


data class GetProduct200ResponseData (

    @SerializedName("product")
    val product: Product? = null,

    @SerializedName("installmentCount")
    val installmentCount: kotlin.Int? = null,

    @SerializedName("installmentValue")
    val installmentValue: java.math.BigDecimal? = null

) {


}

