/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Review

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param averageRating 
 * @param totalCount 
 * @param distribution 
 * @param reviews 
 */


data class GetReviews200ResponseData (

    @SerializedName("averageRating")
    val averageRating: java.math.BigDecimal? = null,

    @SerializedName("totalCount")
    val totalCount: kotlin.Int? = null,

    @SerializedName("distribution")
    val distribution: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerializedName("reviews")
    val reviews: kotlin.collections.List<Review>? = null

) {


}

