/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.ShippingOption

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param options 
 * @param freeShippingMessage 
 */


data class GetShippingOptions200ResponseData (

    @SerializedName("options")
    val options: kotlin.collections.List<ShippingOption>? = null,

    @SerializedName("freeShippingMessage")
    val freeShippingMessage: kotlin.String? = null

) {


}

