/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param slug 
 * @param title 
 * @param content 
 * @param updatedAt 
 */


data class GetStaticPage200ResponseData (

    @SerializedName("slug")
    val slug: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("content")
    val content: kotlin.String? = null,

    @SerializedName("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

