/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.PaymentMethod

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param paymentMethods 
 */


data class ListPaymentMethods200ResponseData (

    @SerializedName("paymentMethods")
    val paymentMethods: kotlin.collections.List<PaymentMethod>? = null

) {


}

