/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param account E-mail ou telefone (últimos 8 dígitos)
 * @param password 
 * @param hasSeenOnboarding 
 */


data class LoginRequest (

    /* E-mail ou telefone (últimos 8 dígitos) */
    @SerializedName("account")
    val account: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String,

    @SerializedName("hasSeenOnboarding")
    val hasSeenOnboarding: kotlin.Boolean? = null

) {


}

