/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Notification

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notification 
 * @param unreadCount 
 */


data class MarkNotificationRead200ResponseData (

    @SerializedName("notification")
    val notification: Notification? = null,

    @SerializedName("unreadCount")
    val unreadCount: kotlin.Int? = null

) {


}

