/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param type 
 * @param title 
 * @param body 
 * @param date 
 * @param isRead 
 * @param deepLink 
 */


data class Notification (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("type")
    val type: Notification.Type? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("body")
    val body: kotlin.String? = null,

    @SerializedName("date")
    val date: java.time.OffsetDateTime? = null,

    @SerializedName("isRead")
    val isRead: kotlin.Boolean? = null,

    @SerializedName("deepLink")
    val deepLink: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ORDER,PROMO,SYSTEM
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "ORDER") ORDER("ORDER"),
        @SerializedName(value = "PROMO") PROMO("PROMO"),
        @SerializedName(value = "SYSTEM") SYSTEM("SYSTEM");
    }

}

