/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.PaymentType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param displayName 
 * @param label 
 */


data class OrderPaymentMethod (

    @SerializedName("type")
    val type: PaymentType? = null,

    @SerializedName("displayName")
    val displayName: kotlin.String? = null,

    @SerializedName("label")
    val label: kotlin.String? = null

) {


}

