/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Address
import com.citybox.api.models.OrderItem
import com.citybox.api.models.OrderPaymentMethod
import com.citybox.api.models.OrderStatus
import com.citybox.api.models.OrderStatusEntry

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param items 
 * @param status 
 * @param deliveryDate 
 * @param address 
 * @param paymentMethod 
 * @param subtotal 
 * @param shipping 
 * @param discount 
 * @param pixDiscount 
 * @param total 
 * @param trackingCode 
 * @param carrier 
 * @param statusHistory 
 * @param createdAt 
 */


data class Order (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("items")
    val items: kotlin.collections.List<OrderItem>? = null,

    @SerializedName("status")
    val status: OrderStatus? = null,

    @SerializedName("deliveryDate")
    val deliveryDate: kotlin.String? = null,

    @SerializedName("address")
    val address: Address? = null,

    @SerializedName("paymentMethod")
    val paymentMethod: OrderPaymentMethod? = null,

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @SerializedName("shipping")
    val shipping: java.math.BigDecimal? = null,

    @SerializedName("discount")
    val discount: java.math.BigDecimal? = null,

    @SerializedName("pixDiscount")
    val pixDiscount: java.math.BigDecimal? = null,

    @SerializedName("total")
    val total: java.math.BigDecimal? = null,

    @SerializedName("trackingCode")
    val trackingCode: kotlin.String? = null,

    @SerializedName("carrier")
    val carrier: kotlin.String? = null,

    @SerializedName("statusHistory")
    val statusHistory: kotlin.collections.List<OrderStatusEntry>? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

