/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Product

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param productId 
 * @param product 
 * @param quantity 
 * @param unitPrice 
 * @param subtotal 
 */


data class OrderItem (

    @SerializedName("productId")
    val productId: kotlin.String? = null,

    @SerializedName("product")
    val product: Product? = null,

    @SerializedName("quantity")
    val quantity: kotlin.Int? = null,

    @SerializedName("unitPrice")
    val unitPrice: java.math.BigDecimal? = null,

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal? = null

) {


}

