/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param page 
 * @param pageSize 
 * @param total 
 */


data class PageMeta (

    @SerializedName("page")
    val page: kotlin.Int? = null,

    @SerializedName("pageSize")
    val pageSize: kotlin.Int? = null,

    @SerializedName("total")
    val total: kotlin.Int? = null

) {


}

