/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.PaymentType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param paymentMethodId Obrigatório quando type=CARD
 * @param cpf Obrigatório quando type=BOLETO
 */


data class PaymentInput (

    @SerializedName("type")
    val type: PaymentType,

    /* Obrigatório quando type=CARD */
    @SerializedName("paymentMethodId")
    val paymentMethodId: kotlin.String? = null,

    /* Obrigatório quando type=BOLETO */
    @SerializedName("cpf")
    val cpf: kotlin.String? = null

) {


}

