/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CardBrand

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param brand 
 * @param lastFour 
 * @param expiry 
 * @param holderName 
 * @param label 
 * @param isDefault 
 */


data class PaymentMethod (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("brand")
    val brand: CardBrand? = null,

    @SerializedName("lastFour")
    val lastFour: kotlin.String? = null,

    @SerializedName("expiry")
    val expiry: kotlin.String? = null,

    @SerializedName("holderName")
    val holderName: kotlin.String? = null,

    @SerializedName("label")
    val label: kotlin.String? = null,

    @SerializedName("isDefault")
    val isDefault: kotlin.Boolean? = null

) {


}

