/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.PaymentType

import com.google.gson.annotations.SerializedName

/**
 * Resultado do pagamento conforme o tipo (PIX/CARD/BOLETO)
 *
 * @param type 
 * @param status 
 * @param paymentMethodId 
 * @param displayName 
 * @param authorizationCode 
 * @param pixQrCodeBase64 
 * @param pixCopyPaste 
 * @param barcode 
 * @param digitableLine 
 * @param dueDate 
 * @param pdfUrl 
 * @param expiresAt 
 */


data class PaymentResult (

    @SerializedName("type")
    val type: PaymentType? = null,

    @SerializedName("status")
    val status: PaymentResult.Status? = null,

    @SerializedName("paymentMethodId")
    val paymentMethodId: kotlin.String? = null,

    @SerializedName("displayName")
    val displayName: kotlin.String? = null,

    @SerializedName("authorizationCode")
    val authorizationCode: kotlin.String? = null,

    @SerializedName("pixQrCodeBase64")
    val pixQrCodeBase64: kotlin.String? = null,

    @SerializedName("pixCopyPaste")
    val pixCopyPaste: kotlin.String? = null,

    @SerializedName("barcode")
    val barcode: kotlin.String? = null,

    @SerializedName("digitableLine")
    val digitableLine: kotlin.String? = null,

    @SerializedName("dueDate")
    val dueDate: java.time.LocalDate? = null,

    @SerializedName("pdfUrl")
    val pdfUrl: java.net.URI? = null,

    @SerializedName("expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: PENDING,APPROVED,DECLINED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "PENDING") PENDING("PENDING"),
        @SerializedName(value = "APPROVED") APPROVED("APPROVED"),
        @SerializedName(value = "DECLINED") DECLINED("DECLINED");
    }

}

