/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param imageUrl 
 * @param price 
 * @param originalPrice 
 * @param discountPercent 
 * @param rating 
 * @param reviewCount 
 * @param isFreeShipping 
 * @param isExpress 
 * @param category 
 * @param categoryId 
 * @param brand 
 * @param specs 
 */


data class Product (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("imageUrl")
    val imageUrl: java.net.URI? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null,

    @SerializedName("originalPrice")
    val originalPrice: java.math.BigDecimal? = null,

    @SerializedName("discountPercent")
    val discountPercent: kotlin.Int? = null,

    @SerializedName("rating")
    val rating: java.math.BigDecimal? = null,

    @SerializedName("reviewCount")
    val reviewCount: kotlin.Int? = null,

    @SerializedName("isFreeShipping")
    val isFreeShipping: kotlin.Boolean? = null,

    @SerializedName("isExpress")
    val isExpress: kotlin.Boolean? = null,

    @SerializedName("category")
    val category: kotlin.String? = null,

    @SerializedName("categoryId")
    val categoryId: kotlin.String? = null,

    @SerializedName("brand")
    val brand: kotlin.String? = null,

    @SerializedName("specs")
    val specs: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

