/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param email 
 * @param phone 
 * @param password 
 * @param confirmPassword 
 * @param acceptedTerms 
 * @param hasSeenOnboarding 
 */


data class RegisterRequest (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("phone")
    val phone: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String,

    @SerializedName("confirmPassword")
    val confirmPassword: kotlin.String,

    @SerializedName("acceptedTerms")
    val acceptedTerms: kotlin.Boolean,

    @SerializedName("hasSeenOnboarding")
    val hasSeenOnboarding: kotlin.Boolean? = null

) {


}

