/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CartItemInput
import com.citybox.api.models.ReturnReason

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param returnId 
 * @param orderId 
 * @param status 
 * @param item 
 * @param reason 
 * @param description 
 * @param createdAt 
 * @param instructions 
 */


data class ReturnDetail (

    @SerializedName("returnId")
    val returnId: kotlin.String? = null,

    @SerializedName("orderId")
    val orderId: kotlin.String? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("item")
    val item: CartItemInput? = null,

    @SerializedName("reason")
    val reason: ReturnReason? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("instructions")
    val instructions: kotlin.String? = null

) {


}

