/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: DEFECT,WRONG_ITEM,REGRET_7_DAYS,NOT_AS_EXPECTED,OTHER
 */

enum class ReturnReason(val value: kotlin.String) {

    @SerializedName(value = "DEFECT")
    DEFECT("DEFECT"),

    @SerializedName(value = "WRONG_ITEM")
    WRONG_ITEM("WRONG_ITEM"),

    @SerializedName(value = "REGRET_7_DAYS")
    REGRET_7_DAYS("REGRET_7_DAYS"),

    @SerializedName(value = "NOT_AS_EXPECTED")
    NOT_AS_EXPECTED("NOT_AS_EXPECTED"),

    @SerializedName(value = "OTHER")
    OTHER("OTHER");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReturnReason) "$data" else null

        /**
         * Returns a valid [ReturnReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReturnReason? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

