/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param author 
 * @param rating 
 * @param date 
 * @param text 
 * @param photoUrls 
 */


data class Review (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("productId")
    val productId: kotlin.String? = null,

    @SerializedName("author")
    val author: kotlin.String? = null,

    @SerializedName("rating")
    val rating: kotlin.Int? = null,

    @SerializedName("date")
    val date: java.time.LocalDate? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("photoUrls")
    val photoUrls: kotlin.collections.List<java.net.URI>? = null

) {


}

