/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pushOrdersEnabled 
 * @param pushPromoEnabled 
 * @param emailPromoEnabled 
 * @param darkTheme 
 * @param language 
 */


data class Settings (

    @SerializedName("pushOrdersEnabled")
    val pushOrdersEnabled: kotlin.Boolean? = null,

    @SerializedName("pushPromoEnabled")
    val pushPromoEnabled: kotlin.Boolean? = null,

    @SerializedName("emailPromoEnabled")
    val emailPromoEnabled: kotlin.Boolean? = null,

    @SerializedName("darkTheme")
    val darkTheme: kotlin.Boolean? = null,

    @SerializedName("language")
    val language: kotlin.String? = null

) {


}

