/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param deliveryEstimate 
 * @param deliveryEstimateDays 
 * @param price 
 * @param isExpress 
 */


data class ShippingOption (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("deliveryEstimate")
    val deliveryEstimate: kotlin.String? = null,

    @SerializedName("deliveryEstimateDays")
    val deliveryEstimateDays: kotlin.Int? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null,

    @SerializedName("isExpress")
    val isExpress: kotlin.Boolean? = null

) {


}

