/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: RELEVANCE,PRICE_ASC,PRICE_DESC,BEST_SELLERS
 */

enum class SortOption(val value: kotlin.String) {

    @SerializedName(value = "RELEVANCE")
    RELEVANCE("RELEVANCE"),

    @SerializedName(value = "PRICE_ASC")
    PRICE_ASC("PRICE_ASC"),

    @SerializedName(value = "PRICE_DESC")
    PRICE_DESC("PRICE_DESC"),

    @SerializedName(value = "BEST_SELLERS")
    BEST_SELLERS("BEST_SELLERS");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SortOption) "$data" else null

        /**
         * Returns a valid [SortOption] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SortOption? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

