/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param isActive 
 * @param planName 
 * @param priceMonthly 
 * @param renewalDate 
 * @param benefits 
 */


data class Subscription (

    @SerializedName("isActive")
    val isActive: kotlin.Boolean? = null,

    @SerializedName("planName")
    val planName: kotlin.String? = null,

    @SerializedName("priceMonthly")
    val priceMonthly: java.math.BigDecimal? = null,

    @SerializedName("renewalDate")
    val renewalDate: java.time.LocalDate? = null,

    @SerializedName("benefits")
    val benefits: kotlin.collections.List<kotlin.String>? = null

) {


}

