/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.OrderStatus
import com.citybox.api.models.TrackingTimelineInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param orderId 
 * @param trackingCode 
 * @param carrier 
 * @param carrierUrl 
 * @param currentStatus 
 * @param estimatedDelivery 
 * @param timeline 
 * @param mapPlaceholderUrl 
 */


data class Tracking (

    @SerializedName("orderId")
    val orderId: kotlin.String? = null,

    @SerializedName("trackingCode")
    val trackingCode: kotlin.String? = null,

    @SerializedName("carrier")
    val carrier: kotlin.String? = null,

    @SerializedName("carrierUrl")
    val carrierUrl: java.net.URI? = null,

    @SerializedName("currentStatus")
    val currentStatus: OrderStatus? = null,

    @SerializedName("estimatedDelivery")
    val estimatedDelivery: java.time.OffsetDateTime? = null,

    @SerializedName("timeline")
    val timeline: kotlin.collections.List<TrackingTimelineInner>? = null,

    @SerializedName("mapPlaceholderUrl")
    val mapPlaceholderUrl: java.net.URI? = null

) {


}

