/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.OrderStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status 
 * @param date 
 * @param location 
 * @param description 
 */


data class TrackingTimelineInner (

    @SerializedName("status")
    val status: OrderStatus? = null,

    @SerializedName("date")
    val date: java.time.OffsetDateTime? = null,

    @SerializedName("location")
    val location: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null

) {


}

