/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 * @param phone 
 * @param avatarUrl 
 * @param avatarInitial 
 * @param isPlus 
 * @param hasSeenOnboarding 
 */


data class User (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("phone")
    val phone: kotlin.String? = null,

    @SerializedName("avatarUrl")
    val avatarUrl: java.net.URI? = null,

    @SerializedName("avatarInitial")
    val avatarInitial: kotlin.String? = null,

    @SerializedName("isPlus")
    val isPlus: kotlin.Boolean? = null,

    @SerializedName("hasSeenOnboarding")
    val hasSeenOnboarding: kotlin.Boolean? = null

) {


}

