/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.CartItemInput

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code 
 * @param subtotal 
 * @param items 
 */


data class ValidateCouponRequest (

    @SerializedName("code")
    val code: kotlin.String,

    @SerializedName("subtotal")
    val subtotal: java.math.BigDecimal,

    @SerializedName("items")
    val items: kotlin.collections.List<CartItemInput>? = null

) {


}

