/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.citybox.api.models

import com.citybox.api.models.Coupon

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param coupon 
 * @param discountAmount 
 * @param isValid 
 */


data class ValidateCoupon200ResponseData (

    @SerializedName("coupon")
    val coupon: Coupon? = null,

    @SerializedName("discountAmount")
    val discountAmount: java.math.BigDecimal? = null,

    @SerializedName("isValid")
    val isValid: kotlin.Boolean? = null

) {


}

