"use client";
import { useState } from 'react';
import { ArrowDown, ArrowUp, Bot, Box, Check, Download, GitBranch, Plus, Settings2, Sparkles, Trash2, TriangleAlert, WandSparkles } from 'lucide-react';
import { BotaoPrimario } from '@/components/ui/BotaoPrimario';
import { ModalConfirmar } from '@/components/ui/ModalConfirmar';
import { baixarArquivo, gerarBpmn, gerarSvg, type EtapaProcesso } from '@/lib/processos-fluxo';

export function EditorFluxo({codigo,nome,etapas,onChange,travado}:{codigo:string;nome:string;etapas:EtapaProcesso[];onChange:(e:EtapaProcesso[])=>void;travado:boolean}) {
  const [selecionada,setSelecionada]=useState(0); const atual=etapas[selecionada]; const [confirmandoRemover,setConfirmandoRemover]=useState(false);
  const atualizar=(dados:Partial<EtapaProcesso>)=>onChange(etapas.map((e,i)=>i===selecionada?{...e,...dados}:e));
  const mover=(dir:-1|1)=>{const alvo=selecionada+dir;if(alvo<0||alvo>=etapas.length)return;const n=[...etapas];[n[selecionada],n[alvo]]=[n[alvo],n[selecionada]];setSelecionada(alvo);onChange(n)};
  const adicionar=()=>{const n=[...etapas,{id:`etapa-${Date.now()}`,nome:'Nova etapa',descricao:'',responsavel:'',prazo:'',sistema:'',tipo:'tarefa' as const,regra:'',excecao:'',gargalo:false,automacao:false,agenteIa:false}];onChange(n);setSelecionada(n.length-1)};
  const remover=()=>{if(!atual)return;const n=etapas.filter((_,i)=>i!==selecionada);onChange(n);setSelecionada(Math.max(0,selecionada-1));setConfirmandoRemover(false)};
  return <div className="pc-flow-editor"><div className="pc-panel pc-flow-head"><div><span className="pc-kicker">Editor operacional</span><h2>Fluxo do processo</h2><p>Selecione uma etapa para completar as informações operacionais.</p></div><div className="pc-flow-actions"><BotaoPrimario variante="secundario" disabled={!etapas.length} onClick={()=>baixarArquivo(`${codigo}.bpmn`,gerarBpmn(codigo,nome,etapas),'application/xml')}><Download size={14}/> BPMN</BotaoPrimario><BotaoPrimario variante="secundario" disabled={!etapas.length} onClick={()=>baixarArquivo(`${codigo}.svg`,gerarSvg(nome,etapas),'image/svg+xml')}><Download size={14}/> SVG</BotaoPrimario>{!travado&&<BotaoPrimario onClick={adicionar}><Plus size={14}/> Etapa</BotaoPrimario>}</div></div>
    <div className="pc-flow-edit-body"><div className="pc-flow-canvas">{etapas.length?etapas.map((e,i)=><button type="button" onClick={()=>setSelecionada(i)} className={`pc-flow-node ${i===selecionada?'ativo':''}`} key={e.id}><span>{e.tipo==='decisao'?<GitBranch/>:e.tipo==='aprovacao'?<Check/>:<Box/>}</span><div><small>{e.tipo} · etapa {i+1}</small><b>{e.nome}</b><em>{e.responsavel||'Responsável não definido'}</em><div>{e.gargalo&&<TriangleAlert/>}{e.automacao&&<WandSparkles/>}{e.agenteIa&&<Bot/>}</div></div></button>):<div className="pc-empty"><GitBranch size={36}/><b>Comece desenhando a primeira etapa</b><BotaoPrimario onClick={adicionar}>Adicionar etapa</BotaoPrimario></div>}</div>
      {atual&&<aside className="pc-step-panel"><header><div><Settings2 size={17}/><b>Propriedades da etapa</b></div>{!travado&&<div><button onClick={()=>mover(-1)} disabled={selecionada===0} title="Mover para cima"><ArrowUp/></button><button onClick={()=>mover(1)} disabled={selecionada===etapas.length-1} title="Mover para baixo"><ArrowDown/></button><button onClick={()=>setConfirmandoRemover(true)} title="Remover"><Trash2/></button></div>}</header><div className="pc-step-fields"><label>Nome<input disabled={travado} value={atual.nome} onChange={e=>atualizar({nome:e.target.value})}/></label><label>Tipo<select disabled={travado} value={atual.tipo} onChange={e=>atualizar({tipo:e.target.value as EtapaProcesso['tipo']})}><option value="tarefa">Tarefa</option><option value="decisao">Decisão</option><option value="aprovacao">Aprovação</option></select></label><label>Descrição<textarea disabled={travado} value={atual.descricao} onChange={e=>atualizar({descricao:e.target.value})}/></label><div className="pc-step-row"><label>Responsável<input disabled={travado} value={atual.responsavel} onChange={e=>atualizar({responsavel:e.target.value})}/></label><label>Prazo<input disabled={travado} value={atual.prazo} onChange={e=>atualizar({prazo:e.target.value})}/></label></div><label>Sistema utilizado<input disabled={travado} value={atual.sistema} onChange={e=>atualizar({sistema:e.target.value})}/></label><label>Regra<textarea disabled={travado} value={atual.regra} onChange={e=>atualizar({regra:e.target.value})}/></label><label>Exceção<textarea disabled={travado} value={atual.excecao} onChange={e=>atualizar({excecao:e.target.value})}/></label><div className="pc-step-checks"><label><input type="checkbox" disabled={travado} checked={atual.gargalo} onChange={e=>atualizar({gargalo:e.target.checked})}/><TriangleAlert/> Gargalo</label><label><input type="checkbox" disabled={travado} checked={atual.automacao} onChange={e=>atualizar({automacao:e.target.checked})}/><WandSparkles/> Automação</label><label><input type="checkbox" disabled={travado} checked={atual.agenteIa} onChange={e=>atualizar({agenteIa:e.target.checked})}/><Sparkles/> Agente IA</label></div></div></aside>}
    </div>{confirmandoRemover&&atual&&<ModalConfirmar titulo="Remover etapa" mensagem={<>Remover a etapa <b>{atual.nome}</b> do fluxo?</>} rotuloConfirmar="Remover" perigo onConfirmar={remover} onFechar={()=>setConfirmandoRemover(false)}/>}</div>;
}
