/**
 * Fonte única das rotas do app. Use em `navigate(...)` / `<Link to=...>` para
 * evitar strings mágicas espalhadas e ter rename seguro.
 * (As definições `<Route path>` em App.tsx usam segmentos relativos próprios.)
 */
export const routes = {
  home: '/',
  search: '/busca',
  category: (id: string) => `/categoria/${id}`,
  product: (id: string) => `/produto/${id}`,
  productReviews: (id: string) => `/produto/${id}/avaliacoes`,
  writeReview: (productId: string) => `/avaliar/${productId}`,
  cart: '/carrinho',
  checkout: '/checkout',
  checkoutAddress: '/checkout/endereco',
  checkoutShipping: '/checkout/envio',
  confirmation: '/confirmacao',
  orders: '/compras',
  order: (id: string) => `/compras/${id}`,
  orderTracking: (id: string) => `/compras/${id}/rastreio`,
  orderReturn: (id: string) => `/compras/${id}/devolucao`,
  favorites: '/favoritos',
  account: '/conta',
  profile: '/conta/perfil',
  addresses: '/conta/enderecos',
  newAddress: '/conta/enderecos/novo',
  editAddress: (id: string) => `/conta/enderecos/${id}`,
  cards: '/conta/cartoes',
  newCard: '/conta/cartoes/novo',
  settings: '/conta/configuracoes',
  subscription: '/conta/citybox-plus',
  notifications: '/conta/notificacoes',
  coupons: '/conta/cupons',
  help: '/conta/ajuda',
  openTicket: '/conta/chamado',
  myTickets: '/conta/chamados',
  chat: '/conta/atendimento',
  staticPage: (slug: string) => `/pagina/${slug}`,
  login: '/login',
  register: '/cadastro',
  forgotPassword: '/esqueci-senha',
  resetPassword: '/redefinir-senha',
  onboarding: '/onboarding',
} as const;
